# Generated by Django 2.0.4 on 2018-06-14 02:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('authorsanonymous', '0001_squashed_0013_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailchimpSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=60)),
                ('newsletter_list', models.CharField(blank=True, max_length=30)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitecopy',
            name='newsletter_body',
            field=wagtail.core.fields.RichTextField(default='\n            <p>Subscribe to our mailing list to receive all our news in your\n            inbox</p>\n            '),
        ),
        migrations.AddField(
            model_name='sitecopy',
            name='newsletter_title',
            field=models.CharField(default='Subscribe to our newsletter', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='header_body',
            field=wagtail.core.fields.RichTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='header_text',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sitecopy',
            name='contact_body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
