# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 05:21
from __future__ import unicode_literals

import authorsanonymous.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorsanonymous', '0002_auto_20180105_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='fancypage',
            name='header_icon',
            field=authorsanonymous.models.ChoiceField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
