# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 12:42
from __future__ import unicode_literals

import authorsanonymous.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('authorsanonymous', '0003_fancypage_header_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_public', models.BooleanField()),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=20)),
                ('instagram_handle', models.CharField(blank=True, max_length=20)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fancypage',
            name='header_body',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='fancypage',
            name='header_icon',
            field=authorsanonymous.models.ChoiceField(help_text="See <a href='http://fontawesome.io/icons/'>Font Awesome</a> for the list of available icons.", max_length=40, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='fancypage',
            name='header_text',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
