# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorsanonymous', '0004_auto_20180105_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
