# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorsanonymous', '0005_auto_20180105_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='header_body',
            field=wagtail.wagtailcore.fields.RichTextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='header_text',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='title',
            field=models.CharField(default='Get in touch', max_length=50),
        ),
    ]
