# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('authorsanonymous', '0006_auto_20180105_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='', help_text='The title shown at the very top of content pages.', max_length=255)),
                ('copyright', models.CharField(default='Your Name Here', help_text='Copyright statement in the footer', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
