# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorsanonymous', '0007_sitecopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecopy',
            name='site_title',
            field=models.CharField(default='Authors Anonymous', help_text='The title shown at the very top of content pages.', max_length=255),
        ),
    ]
