# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorsanonymous', '0008_auto_20180105_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='body',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='title',
        ),
        migrations.AddField(
            model_name='sitecopy',
            name='contact_body',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitecopy',
            name='contact_title',
            field=models.CharField(default='Get in touch', max_length=50),
        ),
    ]
