# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 11:40
from __future__ import unicode_literals

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models

import authorsanonymous.models


class Migration(migrations.Migration):

    dependencies = [
        ('authorsanonymous', '0011_add_body_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', authorsanonymous.models.ChoiceField(help_text="See <a href='http://fontawesome.io/icons/'>Font Awesome</a> for the list of available icons.", max_length=40, verbose_name='Icon')),
                ('text', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='goodreads_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='extraaccounts',
            name='setting',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_accounts', to='authorsanonymous.ContactDetails'),
        ),
    ]
