# Download icons.json from
# https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/icons.yml
#
# Load the JSON data in to Python, then run:
#
# icon_choices = [
#     ('fa{} fa-{}'.format(style[0], name),
#      '{} ({})'.format(icon['label'], style.title()))
#     for name, icon in data.items()
#     for style in icon['styles']]
FONT_AWESOME_ICONS = [
    ('fab fa-500px', '500px (Brands)'),
    ('fab fa-accessible-icon', 'Accessible Icon (Brands)'),
    ('fab fa-accusoft', 'Accusoft (Brands)'),
    ('fas fa-address-book', 'Address Book (Solid)'),
    ('far fa-address-book', 'Address Book (Regular)'),
    ('fas fa-address-card', 'Address Card (Solid)'),
    ('far fa-address-card', 'Address Card (Regular)'),
    ('fas fa-adjust', 'adjust (Solid)'),
    ('fab fa-adn', 'App.net (Brands)'),
    ('fab fa-adversal', 'Adversal (Brands)'),
    ('fab fa-affiliatetheme', 'affiliatetheme (Brands)'),
    ('fab fa-algolia', 'Algolia (Brands)'),
    ('fas fa-align-center', 'align-center (Solid)'),
    ('fas fa-align-justify', 'align-justify (Solid)'),
    ('fas fa-align-left', 'align-left (Solid)'),
    ('fas fa-align-right', 'align-right (Solid)'),
    ('fab fa-amazon', 'Amazon (Brands)'),
    ('fab fa-amazon-pay', 'Amazon Pay (Brands)'),
    ('fas fa-ambulance', 'ambulance (Solid)'),
    ('fas fa-american-sign-language-interpreting', 'American Sign Language Interpreting (Solid)'),
    ('fab fa-amilia', 'Amilia (Brands)'),
    ('fas fa-anchor', 'Anchor (Solid)'),
    ('fab fa-android', 'Android (Brands)'),
    ('fab fa-angellist', 'AngelList (Brands)'),
    ('fas fa-angle-double-down', 'Angle Double Down (Solid)'),
    ('fas fa-angle-double-left', 'Angle Double Left (Solid)'),
    ('fas fa-angle-double-right', 'Angle Double Right (Solid)'),
    ('fas fa-angle-double-up', 'Angle Double Up (Solid)'),
    ('fas fa-angle-down', 'angle-down (Solid)'),
    ('fas fa-angle-left', 'angle-left (Solid)'),
    ('fas fa-angle-right', 'angle-right (Solid)'),
    ('fas fa-angle-up', 'angle-up (Solid)'),
    ('fab fa-angrycreative', 'Angry Creative (Brands)'),
    ('fab fa-angular', 'Angular (Brands)'),
    ('fab fa-app-store', 'App Store (Brands)'),
    ('fab fa-app-store-ios', 'iOS App Store (Brands)'),
    ('fab fa-apper', 'Apper Systems AB (Brands)'),
    ('fab fa-apple', 'Apple (Brands)'),
    ('fab fa-apple-pay', 'Apple Pay (Brands)'),
    ('fas fa-archive', 'Archive (Solid)'),
    ('fas fa-arrow-alt-circle-down', 'Alternate Arrow Circle Down (Solid)'),
    ('far fa-arrow-alt-circle-down', 'Alternate Arrow Circle Down (Regular)'),
    ('fas fa-arrow-alt-circle-left', 'Alternate Arrow Circle Left (Solid)'),
    ('far fa-arrow-alt-circle-left', 'Alternate Arrow Circle Left (Regular)'),
    ('fas fa-arrow-alt-circle-right', 'Alternate Arrow Circle Right (Solid)'),
    ('far fa-arrow-alt-circle-right', 'Alternate Arrow Circle Right (Regular)'),
    ('fas fa-arrow-alt-circle-up', 'Alternate Arrow Circle Up (Solid)'),
    ('far fa-arrow-alt-circle-up', 'Alternate Arrow Circle Up (Regular)'),
    ('fas fa-arrow-circle-down', 'Arrow Circle Down (Solid)'),
    ('fas fa-arrow-circle-left', 'Arrow Circle Left (Solid)'),
    ('fas fa-arrow-circle-right', 'Arrow Circle Right (Solid)'),
    ('fas fa-arrow-circle-up', 'Arrow Circle Up (Solid)'),
    ('fas fa-arrow-down', 'arrow-down (Solid)'),
    ('fas fa-arrow-left', 'arrow-left (Solid)'),
    ('fas fa-arrow-right', 'arrow-right (Solid)'),
    ('fas fa-arrow-up', 'arrow-up (Solid)'),
    ('fas fa-arrows-alt', 'Alternate Arrows (Solid)'),
    ('fas fa-arrows-alt-h', 'Alternate Arrows Horizontal (Solid)'),
    ('fas fa-arrows-alt-v', 'Alternate Arrows Vertical (Solid)'),
    ('fas fa-assistive-listening-systems', 'Assistive Listening Systems (Solid)'),
    ('fas fa-asterisk', 'asterisk (Solid)'),
    ('fab fa-asymmetrik', 'Asymmetrik, Ltd. (Brands)'),
    ('fas fa-at', 'At (Solid)'),
    ('fab fa-audible', 'Audible (Brands)'),
    ('fas fa-audio-description', 'Audio Description (Solid)'),
    ('fab fa-autoprefixer', 'Autoprefixer (Brands)'),
    ('fab fa-avianex', 'avianex (Brands)'),
    ('fab fa-aviato', 'Aviato (Brands)'),
    ('fab fa-aws', 'Amazon Web Services (AWS) (Brands)'),
    ('fas fa-backward', 'backward (Solid)'),
    ('fas fa-balance-scale', 'Balance Scale (Solid)'),
    ('fas fa-ban', 'ban (Solid)'),
    ('fas fa-band-aid', 'Band-Aid (Solid)'),
    ('fab fa-bandcamp', 'Bandcamp (Brands)'),
    ('fas fa-barcode', 'barcode (Solid)'),
    ('fas fa-bars', 'Bars (Solid)'),
    ('fas fa-baseball-ball', 'Baseball Ball (Solid)'),
    ('fas fa-basketball-ball', 'Basketball Ball (Solid)'),
    ('fas fa-bath', 'Bath (Solid)'),
    ('fas fa-battery-empty', 'Battery Empty (Solid)'),
    ('fas fa-battery-full', 'Battery Full (Solid)'),
    ('fas fa-battery-half', 'Battery 1/2 Full (Solid)'),
    ('fas fa-battery-quarter', 'Battery 1/4 Full (Solid)'),
    ('fas fa-battery-three-quarters', 'Battery 3/4 Full (Solid)'),
    ('fas fa-bed', 'Bed (Solid)'),
    ('fas fa-beer', 'beer (Solid)'),
    ('fab fa-behance', 'Behance (Brands)'),
    ('fab fa-behance-square', 'Behance Square (Brands)'),
    ('fas fa-bell', 'bell (Solid)'),
    ('far fa-bell', 'bell (Regular)'),
    ('fas fa-bell-slash', 'Bell Slash (Solid)'),
    ('far fa-bell-slash', 'Bell Slash (Regular)'),
    ('fas fa-bicycle', 'Bicycle (Solid)'),
    ('fab fa-bimobject', 'BIMobject (Brands)'),
    ('fas fa-binoculars', 'Binoculars (Solid)'),
    ('fas fa-birthday-cake', 'Birthday Cake (Solid)'),
    ('fab fa-bitbucket', 'Bitbucket (Brands)'),
    ('fab fa-bitcoin', 'Bitcoin (Brands)'),
    ('fab fa-bity', 'Bity (Brands)'),
    ('fab fa-black-tie', 'Font Awesome Black Tie (Brands)'),
    ('fab fa-blackberry', 'BlackBerry (Brands)'),
    ('fas fa-blind', 'Blind (Solid)'),
    ('fab fa-blogger', 'Blogger (Brands)'),
    ('fab fa-blogger-b', 'Blogger B (Brands)'),
    ('fab fa-bluetooth', 'Bluetooth (Brands)'),
    ('fab fa-bluetooth-b', 'Bluetooth (Brands)'),
    ('fas fa-bold', 'bold (Solid)'),
    ('fas fa-bolt', 'Lightning Bolt (Solid)'),
    ('fas fa-bomb', 'Bomb (Solid)'),
    ('fas fa-book', 'book (Solid)'),
    ('fas fa-bookmark', 'bookmark (Solid)'),
    ('far fa-bookmark', 'bookmark (Regular)'),
    ('fas fa-bowling-ball', 'Bowling Ball (Solid)'),
    ('fas fa-box', 'Box (Solid)'),
    ('fas fa-boxes', 'Boxes (Solid)'),
    ('fas fa-braille', 'Braille (Solid)'),
    ('fas fa-briefcase', 'Briefcase (Solid)'),
    ('fab fa-btc', 'BTC (Brands)'),
    ('fas fa-bug', 'Bug (Solid)'),
    ('fas fa-building', 'Building (Solid)'),
    ('far fa-building', 'Building (Regular)'),
    ('fas fa-bullhorn', 'bullhorn (Solid)'),
    ('fas fa-bullseye', 'Bullseye (Solid)'),
    ('fab fa-buromobelexperte', 'Büromöbel-Experte GmbH & Co. KG. (Brands)'),
    ('fas fa-bus', 'Bus (Solid)'),
    ('fab fa-buysellads', 'BuySellAds (Brands)'),
    ('fas fa-calculator', 'Calculator (Solid)'),
    ('fas fa-calendar', 'Calendar (Solid)'),
    ('far fa-calendar', 'Calendar (Regular)'),
    ('fas fa-calendar-alt', 'Alternate Calendar (Solid)'),
    ('far fa-calendar-alt', 'Alternate Calendar (Regular)'),
    ('fas fa-calendar-check', 'Calendar Check (Solid)'),
    ('far fa-calendar-check', 'Calendar Check (Regular)'),
    ('fas fa-calendar-minus', 'Calendar Minus (Solid)'),
    ('far fa-calendar-minus', 'Calendar Minus (Regular)'),
    ('fas fa-calendar-plus', 'Calendar Plus (Solid)'),
    ('far fa-calendar-plus', 'Calendar Plus (Regular)'),
    ('fas fa-calendar-times', 'Calendar Times (Solid)'),
    ('far fa-calendar-times', 'Calendar Times (Regular)'),
    ('fas fa-camera', 'camera (Solid)'),
    ('fas fa-camera-retro', 'Retro Camera (Solid)'),
    ('fas fa-car', 'Car (Solid)'),
    ('fas fa-caret-down', 'Caret Down (Solid)'),
    ('fas fa-caret-left', 'Caret Left (Solid)'),
    ('fas fa-caret-right', 'Caret Right (Solid)'),
    ('fas fa-caret-square-down', 'Caret Square Down (Solid)'),
    ('far fa-caret-square-down', 'Caret Square Down (Regular)'),
    ('fas fa-caret-square-left', 'Caret Square Left (Solid)'),
    ('far fa-caret-square-left', 'Caret Square Left (Regular)'),
    ('fas fa-caret-square-right', 'Caret Square Right (Solid)'),
    ('far fa-caret-square-right', 'Caret Square Right (Regular)'),
    ('fas fa-caret-square-up', 'Caret Square Up (Solid)'),
    ('far fa-caret-square-up', 'Caret Square Up (Regular)'),
    ('fas fa-caret-up', 'Caret Up (Solid)'),
    ('fas fa-cart-arrow-down', 'Shopping Cart Arrow Down (Solid)'),
    ('fas fa-cart-plus', 'Add to Shopping Cart (Solid)'),
    ('fab fa-cc-amazon-pay', 'Amazon Pay Credit Card (Brands)'),
    ('fab fa-cc-amex', 'American Express Credit Card (Brands)'),
    ('fab fa-cc-apple-pay', 'Apple Pay Credit Card (Brands)'),
    ('fab fa-cc-diners-club', "Diner's Club Credit Card (Brands)"),
    ('fab fa-cc-discover', 'Discover Credit Card (Brands)'),
    ('fab fa-cc-jcb', 'JCB Credit Card (Brands)'),
    ('fab fa-cc-mastercard', 'MasterCard Credit Card (Brands)'),
    ('fab fa-cc-paypal', 'Paypal Credit Card (Brands)'),
    ('fab fa-cc-stripe', 'Stripe Credit Card (Brands)'),
    ('fab fa-cc-visa', 'Visa Credit Card (Brands)'),
    ('fab fa-centercode', 'Centercode (Brands)'),
    ('fas fa-certificate', 'certificate (Solid)'),
    ('fas fa-chart-area', 'Area Chart (Solid)'),
    ('fas fa-chart-bar', 'Bar Chart (Solid)'),
    ('far fa-chart-bar', 'Bar Chart (Regular)'),
    ('fas fa-chart-line', 'Line Chart (Solid)'),
    ('fas fa-chart-pie', 'Pie Chart (Solid)'),
    ('fas fa-check', 'Check (Solid)'),
    ('fas fa-check-circle', 'Check Circle (Solid)'),
    ('far fa-check-circle', 'Check Circle (Regular)'),
    ('fas fa-check-square', 'Check Square (Solid)'),
    ('far fa-check-square', 'Check Square (Regular)'),
    ('fas fa-chess', 'Chess (Solid)'),
    ('fas fa-chess-bishop', 'Chess Bishop (Solid)'),
    ('fas fa-chess-board', 'Chess Board (Solid)'),
    ('fas fa-chess-king', 'Chess King (Solid)'),
    ('fas fa-chess-knight', 'Chess Knight (Solid)'),
    ('fas fa-chess-pawn', 'Chess Pawn (Solid)'),
    ('fas fa-chess-queen', 'Chess Queen (Solid)'),
    ('fas fa-chess-rook', 'Chess Rook (Solid)'),
    ('fas fa-chevron-circle-down', 'Chevron Circle Down (Solid)'),
    ('fas fa-chevron-circle-left', 'Chevron Circle Left (Solid)'),
    ('fas fa-chevron-circle-right', 'Chevron Circle Right (Solid)'),
    ('fas fa-chevron-circle-up', 'Chevron Circle Up (Solid)'),
    ('fas fa-chevron-down', 'chevron-down (Solid)'),
    ('fas fa-chevron-left', 'chevron-left (Solid)'),
    ('fas fa-chevron-right', 'chevron-right (Solid)'),
    ('fas fa-chevron-up', 'chevron-up (Solid)'),
    ('fas fa-child', 'Child (Solid)'),
    ('fab fa-chrome', 'Chrome (Brands)'),
    ('fas fa-circle', 'Circle (Solid)'),
    ('far fa-circle', 'Circle (Regular)'),
    ('fas fa-circle-notch', 'Circle Notched (Solid)'),
    ('fas fa-clipboard', 'Clipboard (Solid)'),
    ('far fa-clipboard', 'Clipboard (Regular)'),
    ('fas fa-clipboard-check', 'Clipboard Check (Solid)'),
    ('fas fa-clipboard-list', 'Clipboard List (Solid)'),
    ('fas fa-clock', 'Clock (Solid)'),
    ('far fa-clock', 'Clock (Regular)'),
    ('fas fa-clone', 'Clone (Solid)'),
    ('far fa-clone', 'Clone (Regular)'),
    ('fas fa-closed-captioning', 'Closed Captioning (Solid)'),
    ('far fa-closed-captioning', 'Closed Captioning (Regular)'),
    ('fas fa-cloud', 'Cloud (Solid)'),
    ('fas fa-cloud-download-alt', 'Cloud Download Alternate (Solid)'),
    ('fas fa-cloud-upload-alt', 'Cloud Upload Alternate (Solid)'),
    ('fab fa-cloudscale', 'cloudscale.ch (Brands)'),
    ('fab fa-cloudsmith', 'Cloudsmith (Brands)'),
    ('fab fa-cloudversify', 'cloudversify (Brands)'),
    ('fas fa-code', 'Code (Solid)'),
    ('fas fa-code-branch', 'Code Branch (Solid)'),
    ('fab fa-codepen', 'Codepen (Brands)'),
    ('fab fa-codiepie', 'Codie Pie (Brands)'),
    ('fas fa-coffee', 'Coffee (Solid)'),
    ('fas fa-cog', 'cog (Solid)'),
    ('fas fa-cogs', 'cogs (Solid)'),
    ('fas fa-columns', 'Columns (Solid)'),
    ('fas fa-comment', 'comment (Solid)'),
    ('far fa-comment', 'comment (Regular)'),
    ('fas fa-comment-alt', 'Alternate Comment (Solid)'),
    ('far fa-comment-alt', 'Alternate Comment (Regular)'),
    ('fas fa-comments', 'comments (Solid)'),
    ('far fa-comments', 'comments (Regular)'),
    ('fas fa-compass', 'Compass (Solid)'),
    ('far fa-compass', 'Compass (Regular)'),
    ('fas fa-compress', 'Compress (Solid)'),
    ('fab fa-connectdevelop', 'Connect Develop (Brands)'),
    ('fab fa-contao', 'Contao (Brands)'),
    ('fas fa-copy', 'Copy (Solid)'),
    ('far fa-copy', 'Copy (Regular)'),
    ('fas fa-copyright', 'Copyright (Solid)'),
    ('far fa-copyright', 'Copyright (Regular)'),
    ('fab fa-cpanel', 'cPanel (Brands)'),
    ('fab fa-creative-commons', 'Creative Commons (Brands)'),
    ('fas fa-credit-card', 'Credit Card (Solid)'),
    ('far fa-credit-card', 'Credit Card (Regular)'),
    ('fas fa-crop', 'crop (Solid)'),
    ('fas fa-crosshairs', 'Crosshairs (Solid)'),
    ('fab fa-css3', 'CSS 3 Logo (Brands)'),
    ('fab fa-css3-alt', 'Alternate CSS3 Logo (Brands)'),
    ('fas fa-cube', 'Cube (Solid)'),
    ('fas fa-cubes', 'Cubes (Solid)'),
    ('fas fa-cut', 'Cut (Solid)'),
    ('fab fa-cuttlefish', 'Cuttlefish (Brands)'),
    ('fab fa-d-and-d', 'Dungeons & Dragons (Brands)'),
    ('fab fa-dashcube', 'DashCube (Brands)'),
    ('fas fa-database', 'Database (Solid)'),
    ('fas fa-deaf', 'Deaf (Solid)'),
    ('fab fa-delicious', 'Delicious Logo (Brands)'),
    ('fab fa-deploydog', 'deploy.dog (Brands)'),
    ('fab fa-deskpro', 'Deskpro (Brands)'),
    ('fas fa-desktop', 'Desktop (Solid)'),
    ('fab fa-deviantart', 'deviantART (Brands)'),
    ('fab fa-digg', 'Digg Logo (Brands)'),
    ('fab fa-digital-ocean', 'Digital Ocean (Brands)'),
    ('fab fa-discord', 'Discord (Brands)'),
    ('fab fa-discourse', 'Discourse (Brands)'),
    ('fas fa-dna', 'DNA (Solid)'),
    ('fab fa-dochub', 'DocHub (Brands)'),
    ('fab fa-docker', 'Docker (Brands)'),
    ('fas fa-dollar-sign', 'Dollar Sign (Solid)'),
    ('fas fa-dolly', 'Dolly (Solid)'),
    ('fas fa-dolly-flatbed', 'Dolly Flatbed (Solid)'),
    ('fas fa-dot-circle', 'Dot Circle (Solid)'),
    ('far fa-dot-circle', 'Dot Circle (Regular)'),
    ('fas fa-download', 'Download (Solid)'),
    ('fab fa-draft2digital', 'Draft2digital (Brands)'),
    ('fab fa-dribbble', 'Dribbble (Brands)'),
    ('fab fa-dribbble-square', 'Dribbble Square (Brands)'),
    ('fab fa-dropbox', 'Dropbox (Brands)'),
    ('fab fa-drupal', 'Drupal Logo (Brands)'),
    ('fab fa-dyalog', 'Dyalog (Brands)'),
    ('fab fa-earlybirds', 'Earlybirds (Brands)'),
    ('fab fa-edge', 'Edge Browser (Brands)'),
    ('fas fa-edit', 'Edit (Solid)'),
    ('far fa-edit', 'Edit (Regular)'),
    ('fas fa-eject', 'eject (Solid)'),
    ('fab fa-elementor', 'Elementor (Brands)'),
    ('fas fa-ellipsis-h', 'Horizontal Ellipsis (Solid)'),
    ('fas fa-ellipsis-v', 'Vertical Ellipsis (Solid)'),
    ('fab fa-ember', 'Ember (Brands)'),
    ('fab fa-empire', 'Galactic Empire (Brands)'),
    ('fas fa-envelope', 'Envelope (Solid)'),
    ('far fa-envelope', 'Envelope (Regular)'),
    ('fas fa-envelope-open', 'Envelope Open (Solid)'),
    ('far fa-envelope-open', 'Envelope Open (Regular)'),
    ('fas fa-envelope-square', 'Envelope Square (Solid)'),
    ('fab fa-envira', 'Envira Gallery (Brands)'),
    ('fas fa-eraser', 'eraser (Solid)'),
    ('fab fa-erlang', 'Erlang (Brands)'),
    ('fab fa-ethereum', 'Ethereum (Brands)'),
    ('fab fa-etsy', 'Etsy (Brands)'),
    ('fas fa-euro-sign', 'Euro Sign (Solid)'),
    ('fas fa-exchange-alt', 'Alternate Exchange (Solid)'),
    ('fas fa-exclamation', 'exclamation (Solid)'),
    ('fas fa-exclamation-circle', 'Exclamation Circle (Solid)'),
    ('fas fa-exclamation-triangle', 'Exclamation Triangle (Solid)'),
    ('fas fa-expand', 'Expand (Solid)'),
    ('fas fa-expand-arrows-alt', 'Alternate Expand Arrows (Solid)'),
    ('fab fa-expeditedssl', 'ExpeditedSSL (Brands)'),
    ('fas fa-external-link-alt', 'Alternate External Link (Solid)'),
    ('fas fa-external-link-square-alt', 'Alternate External Link Square (Solid)'),
    ('fas fa-eye', 'Eye (Solid)'),
    ('fas fa-eye-dropper', 'Eye Dropper (Solid)'),
    ('fas fa-eye-slash', 'Eye Slash (Solid)'),
    ('far fa-eye-slash', 'Eye Slash (Regular)'),
    ('fab fa-facebook', 'Facebook (Brands)'),
    ('fab fa-facebook-f', 'Facebook F (Brands)'),
    ('fab fa-facebook-messenger', 'Facebook Messenger (Brands)'),
    ('fab fa-facebook-square', 'Facebook Square (Brands)'),
    ('fas fa-fast-backward', 'fast-backward (Solid)'),
    ('fas fa-fast-forward', 'fast-forward (Solid)'),
    ('fas fa-fax', 'Fax (Solid)'),
    ('fas fa-female', 'Female (Solid)'),
    ('fas fa-fighter-jet', 'fighter-jet (Solid)'),
    ('fas fa-file', 'File (Solid)'),
    ('far fa-file', 'File (Regular)'),
    ('fas fa-file-alt', 'Alternate File (Solid)'),
    ('far fa-file-alt', 'Alternate File (Regular)'),
    ('fas fa-file-archive', 'Archive File (Solid)'),
    ('far fa-file-archive', 'Archive File (Regular)'),
    ('fas fa-file-audio', 'Audio File (Solid)'),
    ('far fa-file-audio', 'Audio File (Regular)'),
    ('fas fa-file-code', 'Code File (Solid)'),
    ('far fa-file-code', 'Code File (Regular)'),
    ('fas fa-file-excel', 'Excel File (Solid)'),
    ('far fa-file-excel', 'Excel File (Regular)'),
    ('fas fa-file-image', 'Image File (Solid)'),
    ('far fa-file-image', 'Image File (Regular)'),
    ('fas fa-file-pdf', 'PDF File (Solid)'),
    ('far fa-file-pdf', 'PDF File (Regular)'),
    ('fas fa-file-powerpoint', 'Powerpoint File (Solid)'),
    ('far fa-file-powerpoint', 'Powerpoint File (Regular)'),
    ('fas fa-file-video', 'Video File (Solid)'),
    ('far fa-file-video', 'Video File (Regular)'),
    ('fas fa-file-word', 'Word File (Solid)'),
    ('far fa-file-word', 'Word File (Regular)'),
    ('fas fa-film', 'Film (Solid)'),
    ('fas fa-filter', 'Filter (Solid)'),
    ('fas fa-fire', 'fire (Solid)'),
    ('fas fa-fire-extinguisher', 'fire-extinguisher (Solid)'),
    ('fab fa-firefox', 'Firefox (Brands)'),
    ('fas fa-first-aid', 'First Aid (Solid)'),
    ('fab fa-first-order', 'First Order (Brands)'),
    ('fab fa-firstdraft', 'firstdraft (Brands)'),
    ('fas fa-flag', 'flag (Solid)'),
    ('far fa-flag', 'flag (Regular)'),
    ('fas fa-flag-checkered', 'flag-checkered (Solid)'),
    ('fas fa-flask', 'Flask (Solid)'),
    ('fab fa-flickr', 'Flickr (Brands)'),
    ('fab fa-flipboard', 'Flipboard (Brands)'),
    ('fab fa-fly', 'Fly (Brands)'),
    ('fas fa-folder', 'Folder (Solid)'),
    ('far fa-folder', 'Folder (Regular)'),
    ('fas fa-folder-open', 'Folder Open (Solid)'),
    ('far fa-folder-open', 'Folder Open (Regular)'),
    ('fas fa-font', 'font (Solid)'),
    ('fab fa-font-awesome', 'Font Awesome (Brands)'),
    ('fab fa-font-awesome-alt', 'Alternate Font Awesome (Brands)'),
    ('fab fa-font-awesome-flag', 'Font Awesome Flag (Brands)'),
    ('fab fa-fonticons', 'Fonticons (Brands)'),
    ('fab fa-fonticons-fi', 'Fonticons Fi (Brands)'),
    ('fas fa-football-ball', 'Football Ball (Solid)'),
    ('fab fa-fort-awesome', 'Fort Awesome (Brands)'),
    ('fab fa-fort-awesome-alt', 'Alternate Fort Awesome (Brands)'),
    ('fab fa-forumbee', 'Forumbee (Brands)'),
    ('fas fa-forward', 'forward (Solid)'),
    ('fab fa-foursquare', 'Foursquare (Brands)'),
    ('fab fa-free-code-camp', 'Free Code Camp (Brands)'),
    ('fab fa-freebsd', 'FreeBSD (Brands)'),
    ('fas fa-frown', 'Frown (Solid)'),
    ('far fa-frown', 'Frown (Regular)'),
    ('fas fa-futbol', 'Futbol (Solid)'),
    ('far fa-futbol', 'Futbol (Regular)'),
    ('fas fa-gamepad', 'Gamepad (Solid)'),
    ('fas fa-gavel', 'Gavel (Solid)'),
    ('fas fa-gem', 'Gem (Solid)'),
    ('far fa-gem', 'Gem (Regular)'),
    ('fas fa-genderless', 'Genderless (Solid)'),
    ('fab fa-get-pocket', 'Get Pocket (Brands)'),
    ('fab fa-gg', 'GG Currency (Brands)'),
    ('fab fa-gg-circle', 'GG Currency Circle (Brands)'),
    ('fas fa-gift', 'gift (Solid)'),
    ('fab fa-git', 'Git (Brands)'),
    ('fab fa-git-square', 'Git Square (Brands)'),
    ('fab fa-github', 'GitHub (Brands)'),
    ('fab fa-github-alt', 'Alternate GitHub (Brands)'),
    ('fab fa-github-square', 'GitHub Square (Brands)'),
    ('fab fa-gitkraken', 'GitKraken (Brands)'),
    ('fab fa-gitlab', 'GitLab (Brands)'),
    ('fab fa-gitter', 'Gitter (Brands)'),
    ('fas fa-glass-martini', 'Martini Glass (Solid)'),
    ('fab fa-glide', 'Glide (Brands)'),
    ('fab fa-glide-g', 'Glide G (Brands)'),
    ('fas fa-globe', 'Globe (Solid)'),
    ('fab fa-gofore', 'Gofore (Brands)'),
    ('fas fa-golf-ball', 'Golf Ball (Solid)'),
    ('fab fa-goodreads', 'Goodreads (Brands)'),
    ('fab fa-goodreads-g', 'Goodreads G (Brands)'),
    ('fab fa-google', 'Google Logo (Brands)'),
    ('fab fa-google-drive', 'Google Drive (Brands)'),
    ('fab fa-google-play', 'Google Play (Brands)'),
    ('fab fa-google-plus', 'Google Plus (Brands)'),
    ('fab fa-google-plus-g', 'Google Plus G (Brands)'),
    ('fab fa-google-plus-square', 'Google Plus Square (Brands)'),
    ('fab fa-google-wallet', 'Google Wallet (Brands)'),
    ('fas fa-graduation-cap', 'Graduation Cap (Solid)'),
    ('fab fa-gratipay', 'Gratipay (Gittip) (Brands)'),
    ('fab fa-grav', 'Grav (Brands)'),
    ('fab fa-gripfire', 'Gripfire, Inc. (Brands)'),
    ('fab fa-grunt', 'Grunt (Brands)'),
    ('fab fa-gulp', 'Gulp (Brands)'),
    ('fas fa-h-square', 'H Square (Solid)'),
    ('fab fa-hacker-news', 'Hacker News (Brands)'),
    ('fab fa-hacker-news-square', 'Hacker News Square (Brands)'),
    ('fas fa-hand-lizard', 'Lizard (Hand) (Solid)'),
    ('far fa-hand-lizard', 'Lizard (Hand) (Regular)'),
    ('fas fa-hand-paper', 'Paper (Hand) (Solid)'),
    ('far fa-hand-paper', 'Paper (Hand) (Regular)'),
    ('fas fa-hand-peace', 'Peace (Hand) (Solid)'),
    ('far fa-hand-peace', 'Peace (Hand) (Regular)'),
    ('fas fa-hand-point-down', 'Hand Pointing Down (Solid)'),
    ('far fa-hand-point-down', 'Hand Pointing Down (Regular)'),
    ('fas fa-hand-point-left', 'Hand Pointing Left (Solid)'),
    ('far fa-hand-point-left', 'Hand Pointing Left (Regular)'),
    ('fas fa-hand-point-right', 'Hand Pointing Right (Solid)'),
    ('far fa-hand-point-right', 'Hand Pointing Right (Regular)'),
    ('fas fa-hand-point-up', 'Hand Pointing Up (Solid)'),
    ('far fa-hand-point-up', 'Hand Pointing Up (Regular)'),
    ('fas fa-hand-pointer', 'Pointer (Hand) (Solid)'),
    ('far fa-hand-pointer', 'Pointer (Hand) (Regular)'),
    ('fas fa-hand-rock', 'Rock (Hand) (Solid)'),
    ('far fa-hand-rock', 'Rock (Hand) (Regular)'),
    ('fas fa-hand-scissors', 'Scissors (Hand) (Solid)'),
    ('far fa-hand-scissors', 'Scissors (Hand) (Regular)'),
    ('fas fa-hand-spock', 'Spock (Hand) (Solid)'),
    ('far fa-hand-spock', 'Spock (Hand) (Regular)'),
    ('fas fa-handshake', 'Handshake (Solid)'),
    ('far fa-handshake', 'Handshake (Regular)'),
    ('fas fa-hashtag', 'Hashtag (Solid)'),
    ('fas fa-hdd', 'HDD (Solid)'),
    ('far fa-hdd', 'HDD (Regular)'),
    ('fas fa-heading', 'heading (Solid)'),
    ('fas fa-headphones', 'headphones (Solid)'),
    ('fas fa-heart', 'Heart (Solid)'),
    ('far fa-heart', 'Heart (Regular)'),
    ('fas fa-heartbeat', 'Heartbeat (Solid)'),
    ('fab fa-hips', 'Hips (Brands)'),
    ('fab fa-hire-a-helper', 'HireAHelper (Brands)'),
    ('fas fa-history', 'History (Solid)'),
    ('fas fa-hockey-puck', 'Hockey Puck (Solid)'),
    ('fas fa-home', 'home (Solid)'),
    ('fab fa-hooli', 'Hooli (Brands)'),
    ('fas fa-hospital', 'hospital (Solid)'),
    ('far fa-hospital', 'hospital (Regular)'),
    ('fas fa-hospital-symbol', 'Hospital Symbol (Solid)'),
    ('fab fa-hotjar', 'Hotjar (Brands)'),
    ('fas fa-hourglass', 'Hourglass (Solid)'),
    ('far fa-hourglass', 'Hourglass (Regular)'),
    ('fas fa-hourglass-end', 'Hourglass End (Solid)'),
    ('fas fa-hourglass-half', 'Hourglass Half (Solid)'),
    ('fas fa-hourglass-start', 'Hourglass Start (Solid)'),
    ('fab fa-houzz', 'Houzz (Brands)'),
    ('fab fa-html5', 'HTML 5 Logo (Brands)'),
    ('fab fa-hubspot', 'HubSpot (Brands)'),
    ('fas fa-i-cursor', 'I Beam Cursor (Solid)'),
    ('fas fa-id-badge', 'Identification Badge (Solid)'),
    ('far fa-id-badge', 'Identification Badge (Regular)'),
    ('fas fa-id-card', 'Identification Card (Solid)'),
    ('far fa-id-card', 'Identification Card (Regular)'),
    ('fas fa-image', 'Image (Solid)'),
    ('far fa-image', 'Image (Regular)'),
    ('fas fa-images', 'Images (Solid)'),
    ('far fa-images', 'Images (Regular)'),
    ('fab fa-imdb', 'IMDB (Brands)'),
    ('fas fa-inbox', 'inbox (Solid)'),
    ('fas fa-indent', 'Indent (Solid)'),
    ('fas fa-industry', 'Industry (Solid)'),
    ('fas fa-info', 'Info (Solid)'),
    ('fas fa-info-circle', 'Info Circle (Solid)'),
    ('fab fa-instagram', 'Instagram (Brands)'),
    ('fab fa-internet-explorer', 'Internet-explorer (Brands)'),
    ('fab fa-ioxhost', 'ioxhost (Brands)'),
    ('fas fa-italic', 'italic (Solid)'),
    ('fab fa-itunes', 'iTunes (Brands)'),
    ('fab fa-itunes-note', 'Itunes Note (Brands)'),
    ('fab fa-jenkins', 'Jenkis (Brands)'),
    ('fab fa-joget', 'Joget (Brands)'),
    ('fab fa-joomla', 'Joomla Logo (Brands)'),
    ('fab fa-js', 'JavaScript (JS) (Brands)'),
    ('fab fa-js-square', 'JavaScript (JS) Square (Brands)'),
    ('fab fa-jsfiddle', 'jsFiddle (Brands)'),
    ('fas fa-key', 'key (Solid)'),
    ('fas fa-keyboard', 'Keyboard (Solid)'),
    ('far fa-keyboard', 'Keyboard (Regular)'),
    ('fab fa-keycdn', 'KeyCDN (Brands)'),
    ('fab fa-kickstarter', 'Kickstarter (Brands)'),
    ('fab fa-kickstarter-k', 'Kickstarter K (Brands)'),
    ('fab fa-korvue', 'KORVUE (Brands)'),
    ('fas fa-language', 'Language (Solid)'),
    ('fas fa-laptop', 'Laptop (Solid)'),
    ('fab fa-laravel', 'Laravel (Brands)'),
    ('fab fa-lastfm', 'last.fm (Brands)'),
    ('fab fa-lastfm-square', 'last.fm Square (Brands)'),
    ('fas fa-leaf', 'leaf (Solid)'),
    ('fab fa-leanpub', 'Leanpub (Brands)'),
    ('fas fa-lemon', 'Lemon (Solid)'),
    ('far fa-lemon', 'Lemon (Regular)'),
    ('fab fa-less', 'Less (Brands)'),
    ('fas fa-level-down-alt', 'Level Down Alternate (Solid)'),
    ('fas fa-level-up-alt', 'Level Up Alternate (Solid)'),
    ('fas fa-life-ring', 'Life Ring (Solid)'),
    ('far fa-life-ring', 'Life Ring (Regular)'),
    ('fas fa-lightbulb', 'Lightbulb (Solid)'),
    ('far fa-lightbulb', 'Lightbulb (Regular)'),
    ('fab fa-line', 'Line (Brands)'),
    ('fas fa-link', 'Link (Solid)'),
    ('fab fa-linkedin', 'LinkedIn (Brands)'),
    ('fab fa-linkedin-in', 'LinkedIn In (Brands)'),
    ('fab fa-linode', 'Linode (Brands)'),
    ('fab fa-linux', 'Linux (Brands)'),
    ('fas fa-lira-sign', 'Turkish Lira Sign (Solid)'),
    ('fas fa-list', 'List (Solid)'),
    ('fas fa-list-alt', 'List Alternate (Solid)'),
    ('far fa-list-alt', 'List Alternate (Regular)'),
    ('fas fa-list-ol', 'list-ol (Solid)'),
    ('fas fa-list-ul', 'list-ul (Solid)'),
    ('fas fa-location-arrow', 'location-arrow (Solid)'),
    ('fas fa-lock', 'lock (Solid)'),
    ('fas fa-lock-open', 'Lock Open (Solid)'),
    ('fas fa-long-arrow-alt-down', 'Alternate Long Arrow Down (Solid)'),
    ('fas fa-long-arrow-alt-left', 'Alternate Long Arrow Left (Solid)'),
    ('fas fa-long-arrow-alt-right', 'Alternate Long Arrow Right (Solid)'),
    ('fas fa-long-arrow-alt-up', 'Alternate Long Arrow Up (Solid)'),
    ('fas fa-low-vision', 'Low Vision (Solid)'),
    ('fab fa-lyft', 'lyft (Brands)'),
    ('fab fa-magento', 'Magento (Brands)'),
    ('fas fa-magic', 'magic (Solid)'),
    ('fas fa-magnet', 'magnet (Solid)'),
    ('fas fa-male', 'Male (Solid)'),
    ('fas fa-map', 'Map (Solid)'),
    ('far fa-map', 'Map (Regular)'),
    ('fas fa-map-marker', 'map-marker (Solid)'),
    ('fas fa-map-marker-alt', 'Map Marker Alternate (Solid)'),
    ('fas fa-map-pin', 'Map Pin (Solid)'),
    ('fas fa-map-signs', 'Map Signs (Solid)'),
    ('fas fa-mars', 'Mars (Solid)'),
    ('fas fa-mars-double', 'Mars Double (Solid)'),
    ('fas fa-mars-stroke', 'Mars Stroke (Solid)'),
    ('fas fa-mars-stroke-h', 'Mars Stroke Horizontal (Solid)'),
    ('fas fa-mars-stroke-v', 'Mars Stroke Vertical (Solid)'),
    ('fab fa-maxcdn', 'MaxCDN (Brands)'),
    ('fab fa-medapps', 'MedApps (Brands)'),
    ('fab fa-medium', 'Medium (Brands)'),
    ('fab fa-medium-m', 'Medium M (Brands)'),
    ('fas fa-medkit', 'medkit (Solid)'),
    ('fab fa-medrt', 'MRT (Brands)'),
    ('fab fa-meetup', 'Meetup (Brands)'),
    ('fas fa-meh', 'Meh (Solid)'),
    ('far fa-meh', 'Meh (Regular)'),
    ('fas fa-mercury', 'Mercury (Solid)'),
    ('fas fa-microchip', 'Microchip (Solid)'),
    ('fas fa-microphone', 'microphone (Solid)'),
    ('fas fa-microphone-slash', 'Microphone Slash (Solid)'),
    ('fab fa-microsoft', 'Microsoft (Brands)'),
    ('fas fa-minus', 'minus (Solid)'),
    ('fas fa-minus-circle', 'Minus Circle (Solid)'),
    ('fas fa-minus-square', 'Minus Square (Solid)'),
    ('far fa-minus-square', 'Minus Square (Regular)'),
    ('fab fa-mix', 'Mix (Brands)'),
    ('fab fa-mixcloud', 'Mixcloud (Brands)'),
    ('fab fa-mizuni', 'Mizuni (Brands)'),
    ('fas fa-mobile', 'Mobile Phone (Solid)'),
    ('fas fa-mobile-alt', 'Alternate Mobile (Solid)'),
    ('fab fa-modx', 'MODX (Brands)'),
    ('fab fa-monero', 'Monero (Brands)'),
    ('fas fa-money-bill-alt', 'Money Bill Alternate (Solid)'),
    ('far fa-money-bill-alt', 'Money Bill Alternate (Regular)'),
    ('fas fa-moon', 'Moon (Solid)'),
    ('far fa-moon', 'Moon (Regular)'),
    ('fas fa-motorcycle', 'Motorcycle (Solid)'),
    ('fas fa-mouse-pointer', 'Mouse Pointer (Solid)'),
    ('fas fa-music', 'Music (Solid)'),
    ('fab fa-napster', 'Napster (Brands)'),
    ('fas fa-neuter', 'Neuter (Solid)'),
    ('fas fa-newspaper', 'Newspaper (Solid)'),
    ('far fa-newspaper', 'Newspaper (Regular)'),
    ('fab fa-nintendo-switch', 'Nintendo Switch (Brands)'),
    ('fab fa-node', 'Node.js (Brands)'),
    ('fab fa-node-js', 'Node.js JS (Brands)'),
    ('fab fa-npm', 'npm (Brands)'),
    ('fab fa-ns8', 'NS8 (Brands)'),
    ('fab fa-nutritionix', 'Nutritionix (Brands)'),
    ('fas fa-object-group', 'Object Group (Solid)'),
    ('far fa-object-group', 'Object Group (Regular)'),
    ('fas fa-object-ungroup', 'Object Ungroup (Solid)'),
    ('far fa-object-ungroup', 'Object Ungroup (Regular)'),
    ('fab fa-odnoklassniki', 'Odnoklassniki (Brands)'),
    ('fab fa-odnoklassniki-square', 'Odnoklassniki Square (Brands)'),
    ('fab fa-opencart', 'OpenCart (Brands)'),
    ('fab fa-openid', 'OpenID (Brands)'),
    ('fab fa-opera', 'Opera (Brands)'),
    ('fab fa-optin-monster', 'Optin Monster (Brands)'),
    ('fab fa-osi', 'Open Source Initiative (Brands)'),
    ('fas fa-outdent', 'Outdent (Solid)'),
    ('fab fa-page4', 'page4 Corporation (Brands)'),
    ('fab fa-pagelines', 'Pagelines (Brands)'),
    ('fas fa-paint-brush', 'Paint Brush (Solid)'),
    ('fab fa-palfed', 'Palfed (Brands)'),
    ('fas fa-pallet', 'Pallet (Solid)'),
    ('fas fa-paper-plane', 'Paper Plane (Solid)'),
    ('far fa-paper-plane', 'Paper Plane (Regular)'),
    ('fas fa-paperclip', 'Paperclip (Solid)'),
    ('fas fa-paragraph', 'paragraph (Solid)'),
    ('fas fa-paste', 'Paste (Solid)'),
    ('fab fa-patreon', 'Patreon (Brands)'),
    ('fas fa-pause', 'pause (Solid)'),
    ('fas fa-pause-circle', 'Pause Circle (Solid)'),
    ('far fa-pause-circle', 'Pause Circle (Regular)'),
    ('fas fa-paw', 'Paw (Solid)'),
    ('fab fa-paypal', 'Paypal (Brands)'),
    ('fas fa-pen-square', 'Pen Square (Solid)'),
    ('fas fa-pencil-alt', 'Alternate Pencil (Solid)'),
    ('fas fa-percent', 'Percent (Solid)'),
    ('fab fa-periscope', 'Periscope (Brands)'),
    ('fab fa-phabricator', 'Phabricator (Brands)'),
    ('fab fa-phoenix-framework', 'Phoenix Framework (Brands)'),
    ('fas fa-phone', 'Phone (Solid)'),
    ('fas fa-phone-square', 'Phone Square (Solid)'),
    ('fas fa-phone-volume', 'Phone Volume (Solid)'),
    ('fab fa-php', 'PHP (Brands)'),
    ('fab fa-pied-piper', 'Pied Piper Logo (Brands)'),
    ('fab fa-pied-piper-alt', 'Alternate Pied Piper Logo (Brands)'),
    ('fab fa-pied-piper-pp', 'Pied Piper PP Logo (Old) (Brands)'),
    ('fas fa-pills', 'Pills (Solid)'),
    ('fab fa-pinterest', 'Pinterest (Brands)'),
    ('fab fa-pinterest-p', 'Pinterest P (Brands)'),
    ('fab fa-pinterest-square', 'Pinterest Square (Brands)'),
    ('fas fa-plane', 'plane (Solid)'),
    ('fas fa-play', 'play (Solid)'),
    ('fas fa-play-circle', 'Play Circle (Solid)'),
    ('far fa-play-circle', 'Play Circle (Regular)'),
    ('fab fa-playstation', 'PlayStation (Brands)'),
    ('fas fa-plug', 'Plug (Solid)'),
    ('fas fa-plus', 'plus (Solid)'),
    ('fas fa-plus-circle', 'Plus Circle (Solid)'),
    ('fas fa-plus-square', 'Plus Square (Solid)'),
    ('far fa-plus-square', 'Plus Square (Regular)'),
    ('fas fa-podcast', 'Podcast (Solid)'),
    ('fas fa-pound-sign', 'Pound Sign (Solid)'),
    ('fas fa-power-off', 'Power Off (Solid)'),
    ('fas fa-print', 'print (Solid)'),
    ('fab fa-product-hunt', 'Product Hunt (Brands)'),
    ('fab fa-pushed', 'Pushed (Brands)'),
    ('fas fa-puzzle-piece', 'Puzzle Piece (Solid)'),
    ('fab fa-python', 'Python (Brands)'),
    ('fab fa-qq', 'QQ (Brands)'),
    ('fas fa-qrcode', 'qrcode (Solid)'),
    ('fas fa-question', 'Question (Solid)'),
    ('fas fa-question-circle', 'Question Circle (Solid)'),
    ('far fa-question-circle', 'Question Circle (Regular)'),
    ('fas fa-quidditch', 'Quidditch (Solid)'),
    ('fab fa-quinscape', 'QuinScape (Brands)'),
    ('fab fa-quora', 'Quora (Brands)'),
    ('fas fa-quote-left', 'quote-left (Solid)'),
    ('fas fa-quote-right', 'quote-right (Solid)'),
    ('fas fa-random', 'random (Solid)'),
    ('fab fa-ravelry', 'Ravelry (Brands)'),
    ('fab fa-react', 'React (Brands)'),
    ('fab fa-rebel', 'Rebel Alliance (Brands)'),
    ('fas fa-recycle', 'Recycle (Solid)'),
    ('fab fa-red-river', 'red river (Brands)'),
    ('fab fa-reddit', 'reddit Logo (Brands)'),
    ('fab fa-reddit-alien', 'reddit Alien (Brands)'),
    ('fab fa-reddit-square', 'reddit Square (Brands)'),
    ('fas fa-redo', 'Redo (Solid)'),
    ('fas fa-redo-alt', 'Alternate Redo (Solid)'),
    ('fas fa-registered', 'Registered Trademark (Solid)'),
    ('far fa-registered', 'Registered Trademark (Regular)'),
    ('fab fa-rendact', 'Rendact (Brands)'),
    ('fab fa-renren', 'Renren (Brands)'),
    ('fas fa-reply', 'Reply (Solid)'),
    ('fas fa-reply-all', 'reply-all (Solid)'),
    ('fab fa-replyd', 'replyd (Brands)'),
    ('fab fa-resolving', 'Resolving (Brands)'),
    ('fas fa-retweet', 'Retweet (Solid)'),
    ('fas fa-road', 'road (Solid)'),
    ('fas fa-rocket', 'rocket (Solid)'),
    ('fab fa-rocketchat', 'Rocket.Chat (Brands)'),
    ('fab fa-rockrms', 'Rockrms (Brands)'),
    ('fas fa-rss', 'rss (Solid)'),
    ('fas fa-rss-square', 'RSS Square (Solid)'),
    ('fas fa-ruble-sign', 'Ruble Sign (Solid)'),
    ('fas fa-rupee-sign', 'Indian Rupee Sign (Solid)'),
    ('fab fa-safari', 'Safari (Brands)'),
    ('fab fa-sass', 'Sass (Brands)'),
    ('fas fa-save', 'Save (Solid)'),
    ('far fa-save', 'Save (Regular)'),
    ('fab fa-schlix', 'SCHLIX (Brands)'),
    ('fab fa-scribd', 'Scribd (Brands)'),
    ('fas fa-search', 'Search (Solid)'),
    ('fas fa-search-minus', 'Search Minus (Solid)'),
    ('fas fa-search-plus', 'Search Plus (Solid)'),
    ('fab fa-searchengin', 'Searchengin (Brands)'),
    ('fab fa-sellcast', 'Sellcast (Brands)'),
    ('fab fa-sellsy', 'Sellsy (Brands)'),
    ('fas fa-server', 'Server (Solid)'),
    ('fab fa-servicestack', 'Servicestack (Brands)'),
    ('fas fa-share', 'Share (Solid)'),
    ('fas fa-share-alt', 'Alternate Share (Solid)'),
    ('fas fa-share-alt-square', 'Alternate Share Square (Solid)'),
    ('fas fa-share-square', 'Share Square (Solid)'),
    ('far fa-share-square', 'Share Square (Regular)'),
    ('fas fa-shekel-sign', 'Shekel Sign (Solid)'),
    ('fas fa-shield-alt', 'Alternate Shield (Solid)'),
    ('fas fa-ship', 'Ship (Solid)'),
    ('fas fa-shipping-fast', 'Shipping Fast (Solid)'),
    ('fab fa-shirtsinbulk', 'Shirts in Bulk (Brands)'),
    ('fas fa-shopping-bag', 'Shopping Bag (Solid)'),
    ('fas fa-shopping-basket', 'Shopping Basket (Solid)'),
    ('fas fa-shopping-cart', 'shopping-cart (Solid)'),
    ('fas fa-shower', 'Shower (Solid)'),
    ('fas fa-sign-in-alt', 'Alternate Sign In (Solid)'),
    ('fas fa-sign-language', 'Sign Language (Solid)'),
    ('fas fa-sign-out-alt', 'Alternate Sign Out (Solid)'),
    ('fas fa-signal', 'signal (Solid)'),
    ('fab fa-simplybuilt', 'SimplyBuilt (Brands)'),
    ('fab fa-sistrix', 'SISTRIX (Brands)'),
    ('fas fa-sitemap', 'Sitemap (Solid)'),
    ('fab fa-skyatlas', 'skyatlas (Brands)'),
    ('fab fa-skype', 'Skype (Brands)'),
    ('fab fa-slack', 'Slack Logo (Brands)'),
    ('fab fa-slack-hash', 'Slack Hashtag (Brands)'),
    ('fas fa-sliders-h', 'Horizontal Sliders (Solid)'),
    ('fab fa-slideshare', 'Slideshare (Brands)'),
    ('fas fa-smile', 'Smile (Solid)'),
    ('far fa-smile', 'Smile (Regular)'),
    ('fab fa-snapchat', 'Snapchat (Brands)'),
    ('fab fa-snapchat-ghost', 'Snapchat Ghost (Brands)'),
    ('fab fa-snapchat-square', 'Snapchat Square (Brands)'),
    ('fas fa-snowflake', 'Snowflake (Solid)'),
    ('far fa-snowflake', 'Snowflake (Regular)'),
    ('fas fa-sort', 'Sort (Solid)'),
    ('fas fa-sort-alpha-down', 'Sort Alpha Down (Solid)'),
    ('fas fa-sort-alpha-up', 'Sort Alpha Up (Solid)'),
    ('fas fa-sort-amount-down', 'Sort Amount Down (Solid)'),
    ('fas fa-sort-amount-up', 'Sort Amount Up (Solid)'),
    ('fas fa-sort-down', 'Sort Down (Descending) (Solid)'),
    ('fas fa-sort-numeric-down', 'Sort Numeric Down (Solid)'),
    ('fas fa-sort-numeric-up', 'Sort Numeric Up (Solid)'),
    ('fas fa-sort-up', 'Sort Up (Ascending) (Solid)'),
    ('fab fa-soundcloud', 'SoundCloud (Brands)'),
    ('fas fa-space-shuttle', 'Space Shuttle (Solid)'),
    ('fab fa-speakap', 'Speakap (Brands)'),
    ('fas fa-spinner', 'Spinner (Solid)'),
    ('fab fa-spotify', 'Spotify (Brands)'),
    ('fas fa-square', 'Square (Solid)'),
    ('far fa-square', 'Square (Regular)'),
    ('fas fa-square-full', 'Square Full (Solid)'),
    ('fab fa-stack-exchange', 'Stack Exchange (Brands)'),
    ('fab fa-stack-overflow', 'Stack Overflow (Brands)'),
    ('fas fa-star', 'Star (Solid)'),
    ('far fa-star', 'Star (Regular)'),
    ('fas fa-star-half', 'star-half (Solid)'),
    ('far fa-star-half', 'star-half (Regular)'),
    ('fab fa-staylinked', 'StayLinked (Brands)'),
    ('fab fa-steam', 'Steam (Brands)'),
    ('fab fa-steam-square', 'Steam Square (Brands)'),
    ('fab fa-steam-symbol', 'Steam Symbol (Brands)'),
    ('fas fa-step-backward', 'step-backward (Solid)'),
    ('fas fa-step-forward', 'step-forward (Solid)'),
    ('fas fa-stethoscope', 'Stethoscope (Solid)'),
    ('fab fa-sticker-mule', 'Sticker Mule (Brands)'),
    ('fas fa-sticky-note', 'Sticky Note (Solid)'),
    ('far fa-sticky-note', 'Sticky Note (Regular)'),
    ('fas fa-stop', 'stop (Solid)'),
    ('fas fa-stop-circle', 'Stop Circle (Solid)'),
    ('far fa-stop-circle', 'Stop Circle (Regular)'),
    ('fas fa-stopwatch', 'Stopwatch (Solid)'),
    ('fab fa-strava', 'Strava (Brands)'),
    ('fas fa-street-view', 'Street View (Solid)'),
    ('fas fa-strikethrough', 'Strikethrough (Solid)'),
    ('fab fa-stripe', 'Stripe (Brands)'),
    ('fab fa-stripe-s', 'Stripe S (Brands)'),
    ('fab fa-studiovinari', 'Studio Vinari (Brands)'),
    ('fab fa-stumbleupon', 'StumbleUpon Logo (Brands)'),
    ('fab fa-stumbleupon-circle', 'StumbleUpon Circle (Brands)'),
    ('fas fa-subscript', 'subscript (Solid)'),
    ('fas fa-subway', 'Subway (Solid)'),
    ('fas fa-suitcase', 'Suitcase (Solid)'),
    ('fas fa-sun', 'Sun (Solid)'),
    ('far fa-sun', 'Sun (Regular)'),
    ('fab fa-superpowers', 'Superpowers (Brands)'),
    ('fas fa-superscript', 'superscript (Solid)'),
    ('fab fa-supple', 'Supple (Brands)'),
    ('fas fa-sync', 'Sync (Solid)'),
    ('fas fa-sync-alt', 'Alternate Sync (Solid)'),
    ('fas fa-syringe', 'Syringe (Solid)'),
    ('fas fa-table', 'table (Solid)'),
    ('fas fa-table-tennis', 'Table Tennis (Solid)'),
    ('fas fa-tablet', 'tablet (Solid)'),
    ('fas fa-tablet-alt', 'Alternate Tablet (Solid)'),
    ('fas fa-tachometer-alt', 'Alternate Tachometer (Solid)'),
    ('fas fa-tag', 'tag (Solid)'),
    ('fas fa-tags', 'tags (Solid)'),
    ('fas fa-tasks', 'Tasks (Solid)'),
    ('fas fa-taxi', 'Taxi (Solid)'),
    ('fab fa-telegram', 'Telegram (Brands)'),
    ('fab fa-telegram-plane', 'Telegram Plane (Brands)'),
    ('fab fa-tencent-weibo', 'Tencent Weibo (Brands)'),
    ('fas fa-terminal', 'Terminal (Solid)'),
    ('fas fa-text-height', 'text-height (Solid)'),
    ('fas fa-text-width', 'text-width (Solid)'),
    ('fas fa-th', 'th (Solid)'),
    ('fas fa-th-large', 'th-large (Solid)'),
    ('fas fa-th-list', 'th-list (Solid)'),
    ('fab fa-themeisle', 'ThemeIsle (Brands)'),
    ('fas fa-thermometer', 'Thermometer (Solid)'),
    ('fas fa-thermometer-empty', 'Thermometer Empty (Solid)'),
    ('fas fa-thermometer-full', 'Thermometer Full (Solid)'),
    ('fas fa-thermometer-half', 'Thermometer 1/2 Full (Solid)'),
    ('fas fa-thermometer-quarter', 'Thermometer 1/4 Full (Solid)'),
    ('fas fa-thermometer-three-quarters', 'Thermometer 3/4 Full (Solid)'),
    ('fas fa-thumbs-down', 'thumbs-down (Solid)'),
    ('far fa-thumbs-down', 'thumbs-down (Regular)'),
    ('fas fa-thumbs-up', 'thumbs-up (Solid)'),
    ('far fa-thumbs-up', 'thumbs-up (Regular)'),
    ('fas fa-thumbtack', 'Thumbtack (Solid)'),
    ('fas fa-ticket-alt', 'Alternate Ticket (Solid)'),
    ('fas fa-times', 'Times (Solid)'),
    ('fas fa-times-circle', 'Times Circle (Solid)'),
    ('far fa-times-circle', 'Times Circle (Regular)'),
    ('fas fa-tint', 'tint (Solid)'),
    ('fas fa-toggle-off', 'Toggle Off (Solid)'),
    ('fas fa-toggle-on', 'Toggle On (Solid)'),
    ('fas fa-trademark', 'Trademark (Solid)'),
    ('fas fa-train', 'Train (Solid)'),
    ('fas fa-transgender', 'Transgender (Solid)'),
    ('fas fa-transgender-alt', 'Alternate Transgender (Solid)'),
    ('fas fa-trash', 'Trash (Solid)'),
    ('fas fa-trash-alt', 'Alternate Trash (Solid)'),
    ('far fa-trash-alt', 'Alternate Trash (Regular)'),
    ('fas fa-tree', 'Tree (Solid)'),
    ('fab fa-trello', 'Trello (Brands)'),
    ('fab fa-tripadvisor', 'TripAdvisor (Brands)'),
    ('fas fa-trophy', 'trophy (Solid)'),
    ('fas fa-truck', 'truck (Solid)'),
    ('fas fa-tty', 'TTY (Solid)'),
    ('fab fa-tumblr', 'Tumblr (Brands)'),
    ('fab fa-tumblr-square', 'Tumblr Square (Brands)'),
    ('fas fa-tv', 'Television (Solid)'),
    ('fab fa-twitch', 'Twitch (Brands)'),
    ('fab fa-twitter', 'Twitter (Brands)'),
    ('fab fa-twitter-square', 'Twitter Square (Brands)'),
    ('fab fa-typo3', 'Typo3 (Brands)'),
    ('fab fa-uber', 'Uber (Brands)'),
    ('fab fa-uikit', 'UIkit (Brands)'),
    ('fas fa-umbrella', 'Umbrella (Solid)'),
    ('fas fa-underline', 'Underline (Solid)'),
    ('fas fa-undo', 'Undo (Solid)'),
    ('fas fa-undo-alt', 'Alternate Undo (Solid)'),
    ('fab fa-uniregistry', 'Uniregistry (Brands)'),
    ('fas fa-universal-access', 'Universal Access (Solid)'),
    ('fas fa-university', 'University (Solid)'),
    ('fas fa-unlink', 'unlink (Solid)'),
    ('fas fa-unlock', 'unlock (Solid)'),
    ('fas fa-unlock-alt', 'Alternate Unlock (Solid)'),
    ('fab fa-untappd', 'Untappd (Brands)'),
    ('fas fa-upload', 'Upload (Solid)'),
    ('fab fa-usb', 'USB (Brands)'),
    ('fas fa-user', 'User (Solid)'),
    ('far fa-user', 'User (Regular)'),
    ('fas fa-user-circle', 'User Circle (Solid)'),
    ('far fa-user-circle', 'User Circle (Regular)'),
    ('fas fa-user-md', 'user-md (Solid)'),
    ('fas fa-user-plus', 'Add User (Solid)'),
    ('fas fa-user-secret', 'User Secret (Solid)'),
    ('fas fa-user-times', 'Remove User (Solid)'),
    ('fas fa-users', 'Users (Solid)'),
    ('fab fa-ussunnah', 'us-Sunnah Foundation (Brands)'),
    ('fas fa-utensil-spoon', 'Utensil Spoon (Solid)'),
    ('fas fa-utensils', 'Utensils (Solid)'),
    ('fab fa-vaadin', 'Vaadin (Brands)'),
    ('fas fa-venus', 'Venus (Solid)'),
    ('fas fa-venus-double', 'Venus Double (Solid)'),
    ('fas fa-venus-mars', 'Venus Mars (Solid)'),
    ('fab fa-viacoin', 'Viacoin (Brands)'),
    ('fab fa-viadeo', 'Viadeo (Brands)'),
    ('fab fa-viadeo-square', 'Viadeo Square (Brands)'),
    ('fab fa-viber', 'Viber (Brands)'),
    ('fas fa-video', 'Video (Solid)'),
    ('fab fa-vimeo', 'Vimeo (Brands)'),
    ('fab fa-vimeo-square', 'Vimeo Square (Brands)'),
    ('fab fa-vimeo-v', 'Vimeo (Brands)'),
    ('fab fa-vine', 'Vine (Brands)'),
    ('fab fa-vk', 'VK (Brands)'),
    ('fab fa-vnv', 'VNV (Brands)'),
    ('fas fa-volleyball-ball', 'Volleyball Ball (Solid)'),
    ('fas fa-volume-down', 'volume-down (Solid)'),
    ('fas fa-volume-off', 'volume-off (Solid)'),
    ('fas fa-volume-up', 'volume-up (Solid)'),
    ('fab fa-vuejs', 'Vue.js (Brands)'),
    ('fas fa-warehouse', 'Warehouse (Solid)'),
    ('fab fa-weibo', 'Weibo (Brands)'),
    ('fas fa-weight', 'Weight (Solid)'),
    ('fab fa-weixin', 'Weixin (WeChat) (Brands)'),
    ('fab fa-whatsapp', "What's App (Brands)"),
    ('fab fa-whatsapp-square', "What's App Square (Brands)"),
    ('fas fa-wheelchair', 'Wheelchair (Solid)'),
    ('fab fa-whmcs', 'WHMCS (Brands)'),
    ('fas fa-wifi', 'WiFi (Solid)'),
    ('fab fa-wikipedia-w', 'Wikipedia W (Brands)'),
    ('fas fa-window-close', 'Window Close (Solid)'),
    ('far fa-window-close', 'Window Close (Regular)'),
    ('fas fa-window-maximize', 'Window Maximize (Solid)'),
    ('far fa-window-maximize', 'Window Maximize (Regular)'),
    ('fas fa-window-minimize', 'Window Minimize (Solid)'),
    ('far fa-window-minimize', 'Window Minimize (Regular)'),
    ('fas fa-window-restore', 'Window Restore (Solid)'),
    ('far fa-window-restore', 'Window Restore (Regular)'),
    ('fab fa-windows', 'Windows (Brands)'),
    ('fas fa-won-sign', 'Won Sign (Solid)'),
    ('fab fa-wordpress', 'WordPress Logo (Brands)'),
    ('fab fa-wordpress-simple', 'Wordpress Simple (Brands)'),
    ('fab fa-wpbeginner', 'WPBeginner (Brands)'),
    ('fab fa-wpexplorer', 'WPExplorer (Brands)'),
    ('fab fa-wpforms', 'WPForms (Brands)'),
    ('fas fa-wrench', 'Wrench (Solid)'),
    ('fab fa-xbox', 'Xbox (Brands)'),
    ('fab fa-xing', 'Xing (Brands)'),
    ('fab fa-xing-square', 'Xing Square (Brands)'),
    ('fab fa-y-combinator', 'Y Combinator (Brands)'),
    ('fab fa-yahoo', 'Yahoo Logo (Brands)'),
    ('fab fa-yandex', 'Yandex (Brands)'),
    ('fab fa-yandex-international', 'Yandex International (Brands)'),
    ('fab fa-yelp', 'Yelp (Brands)'),
    ('fas fa-yen-sign', 'Yen Sign (Solid)'),
    ('fab fa-yoast', 'Yoast (Brands)'),
    ('fab fa-youtube', 'YouTube (Brands)'),
    ('fab fa-youtube-square', 'YouTube Square (Brands)'),
]
