FONT_AWESOME_ICONS = [
    ('fa-500px', "500px"),
    ('fa-accessible-icon', "Accessible icon"),
    ('fa-accusoft', "Accusoft"),
    ('fa-address-book', "Address book"),
    ('fa-address-book', "Address book"),
    ('fa-address-card', "Address card"),
    ('fa-address-card', "Address card"),
    ('fa-adjust', "Adjust"),
    ('fa-adn', "ADN"),
    ('fa-adversal', "Adversal"),
    ('fa-affiliatetheme', "Affiliatetheme"),
    ('fa-algolia', "Algolia"),
    ('fa-align-center', "Align center"),
    ('fa-align-justify', "Align justify"),
    ('fa-align-left', "Align left"),
    ('fa-align-right', "Align right"),
    ('fa-amazon', "Amazon"),
    ('fa-amazon-pay', "Amazon Pay"),
    ('fa-ambulance', "Ambulance"),
    ('fa-american-sign-language-interpreting', "American sign language interpreting"),
    ('fa-amilia', "Amilia"),
    ('fa-anchor', "Anchor"),
    ('fa-android', "Android"),
    ('fab fa-angellist', "Angel List"),
    ('fa-angle-double-down', "Angle double down"),
    ('fa-angle-double-left', "Angle double left"),
    ('fa-angle-double-right', "Angle double right"),
    ('fa-angle-double-up', "Angle double up"),
    ('fa-angle-down', "Angle down"),
    ('fa-angle-left', "Angle left"),
    ('fa-angle-right', "Angle right"),
    ('fa-angle-up', "Angle up"),
    ('fa-angrycreative', "Angry Creative"),
    ('fa-angular', "Angular"),
    ('fa-app-store', "App store"),
    ('fa-app-store-ios', "App store iOS"),
    ('fa-apper', "Apper"),
    ('fa-apple', "Apple"),
    ('fa-apple-pay', "Apple Pay"),
    ('fa-archive', "Archive"),
    ('fa-arrow-alt-circle-down', "Arrow alt circle down"),
    ('fa-arrow-alt-circle-down', "Arrow alt circle down"),
    ('fa-arrow-alt-circle-left', "Arrow alt circle left"),
    ('fa-arrow-alt-circle-left', "Arrow alt circle left"),
    ('fa-arrow-alt-circle-right', "Arrow alt circle right"),
    ('fa-arrow-alt-circle-right', "Arrow alt circle right"),
    ('fa-arrow-alt-circle-up', "Arrow alt circle up"),
    ('fa-arrow-alt-circle-up', "Arrow alt circle up"),
    ('fa-arrow-circle-down', "Arrow circle down"),
    ('fa-arrow-circle-left', "Arrow circle left"),
    ('fa-arrow-circle-right', "Arrow circle right"),
    ('fa-arrow-circle-up', "Arrow circle up"),
    ('fa-arrow-down', "Arrow down"),
    ('fa-arrow-left', "Arrow left"),
    ('fa-arrow-right', "Arrow right"),
    ('fa-arrow-up', "Arrow up"),
    ('fa-arrows-alt', "Arrows alt"),
    ('fa-arrows-alt-h', "Arrows alt horizontal"),
    ('fa-arrows-alt-v', "Arrows alt vertical"),
    ('fa-assistive-listening-systems', "Assistive listening systems"),
    ('fa-asterisk', "Asterisk"),
    ('fa-asymmetrik', "Asymmetrik"),
    ('fa-at', "At"),
    ('fa-audible', "Audible"),
    ('fa-audio-description', "Audio description"),
    ('fa-autoprefixer', "Autoprefixer"),
    ('fa-avianex', "Avianex"),
    ('fa-aviato', "Aviato"),
    ('fa-aws', "AWS"),
    ('fa-backward', "Backward"),
    ('fa-balance-scale', "Balance scale"),
    ('fa-ban', "Ban"),
    ('fa-bandcamp', "Bandcamp"),
    ('fa-barcode', "Barcode"),
    ('fa-bars', "Bars"),
    ('fa-baseball-ball', "Baseball ball"),
    ('fa-basketball-ball', "Basketball ball"),
    ('fa-bath', "Bath"),
    ('fa-battery-empty', "Battery empty"),
    ('fa-battery-full', "Battery full"),
    ('fa-battery-half', "Battery half"),
    ('fa-battery-quarter', "Battery quarter"),
    ('fa-battery-three-quarters', "Battery three quarters"),
    ('fa-bed', "Bed"),
    ('fa-beer', "Beer"),
    ('fa-behance', "Behance"),
    ('fa-behance-square', "Behance square"),
    ('fa-bell', "Bell"),
    ('fa-bell-slash', "Bell slash"),
    ('fa-bicycle', "Bicycle"),
    ('fa-bimobject', "BIMobject"),
    ('fa-binoculars', "Binoculars"),
    ('fa-birthday-cake', "Birthday cake"),
    ('fa-bitbucket', "Bitbucket"),
    ('fa-bitcoin', "Bitcoin"),
    ('fa-bity', "Bity"),
    ('fa-black-tie', "Black tie"),
    ('fa-blackberry', "Blackberry"),
    ('fa-blind', "Blind"),
    ('fa-blogger', "Blogger"),
    ('fa-blogger-b', "Blogger alt"),
    ('fa-bluetooth', "Bluetooth"),
    ('fa-bluetooth-b', "Bluetooth alt"),
    ('fa-bold', "Bold"),
    ('fa-bolt', "Bolt"),
    ('fa-bomb', "Bomb"),
    ('fa-book', "Book"),
    ('fa-bookmark', "Bookmark"),
    ('fa-bookmark', "Bookmark"),
    ('fa-bowling-ball', "Bowling ball"),
    ('fa-braille', "Braille"),
    ('fa-briefcase', "Briefcase"),
    ('fa-btc', "BTC"),
    ('fa-bug', "Bug"),
    ('fa-building', "Building"),
    ('fa-bullhorn', "Bullhorn"),
    ('fa-bullseye', "Bullseye"),
    ('fa-buromobelexperte', "Buromobelexperte"),
    ('fa-bus', "Bus"),
    ('fa-buysellads', "BuySellAds"),
    ('fa-calculator', "Calculator"),
    ('fa-calendar', "Calendar"),
    ('fa-calendar-alt', "Calendar alt"),
    ('fa-calendar-check', "Calendar check"),
    ('fa-calendar-minus', "Calendar minus"),
    ('fa-calendar-plus', "Calendar plus"),
    ('fa-calendar-times', "Calendar times"),
    ('fa-camera', "Camera"),
    ('fa-camera-retro', "Camera retro"),
    ('fa-car', "Car"),
    ('fa-caret-down', "Caret down"),
    ('fa-caret-left', "Caret left"),
    ('fa-caret-right', "Caret right"),
    ('fa-caret-square-down', "Caret square down"),
    ('fa-caret-square-left', "Caret square left"),
    ('fa-caret-square-right', "Caret square right"),
    ('fa-caret-square-up', "Caret square up"),
    ('fa-caret-up', "Caret up"),
    ('fa-cart-arrow-down', "Cart arrow down"),
    ('fa-cart-plus', "Cart plus"),
    ('fa-cc-amazon-pay', "CC Amazon Pay"),
    ('fa-cc-amex', "CC AMEX"),
    ('fa-cc-apple-pay', "CC Apple Pay"),
    ('fa-cc-diners-club', "CC Diners Club"),
    ('fa-cc-discover', "CC Discover"),
    ('fa-cc-jcb', "CC JCB"),
    ('fa-cc-mastercard', "CC Mastercard"),
    ('fa-cc-paypal', "CC PayPal"),
    ('fa-cc-stripe', "CC Stripe"),
    ('fa-cc-visa', "CC VISA"),
    ('fa-centercode', "Centercode"),
    ('fa-certificate', "Certificate"),
    ('fa-chart-area', "Chart area"),
    ('fa-chart-bar', "Chart bar"),
    ('fa-chart-bar', "Chart bar"),
    ('fa-chart-line', "Chart line"),
    ('fa-chart-pie', "Chart pie"),
    ('fa-check', "Check"),
    ('fa-check-circle', "Check circle"),
    ('fa-check-square', "Check square"),
    ('fa-chess', "Chess"),
    ('fa-chess-bishop', "Chess bishop"),
    ('fa-chess-board', "Chess board"),
    ('fa-chess-king', "Chess king"),
    ('fa-chess-knight', "Chess knight"),
    ('fa-chess-pawn', "Chess pawn"),
    ('fa-chess-queen', "Chess queen"),
    ('fa-chess-rook', "Chess rook"),
    ('fa-chevron-circle-down', "Chevron circle down"),
    ('fa-chevron-circle-left', "Chevron circle left"),
    ('fa-chevron-circle-right', "Chevron circle right"),
    ('fa-chevron-circle-up', "Chevron circle up"),
    ('fa-chevron-down', "Chevron down"),
    ('fa-chevron-left', "Chevron left"),
    ('fa-chevron-right', "Chevron right"),
    ('fa-chevron-up', "Chevron up"),
    ('fa-child', "Child"),
    ('fa-chrome', "Chrome"),
    ('fa-circle', "Circle"),
    ('fa-circle-notch', "Circle notch"),
    ('fa-clipboard', "Clipboard"),
    ('fa-clock', "Clock"),
    ('fa-clone', "Clone"),
    ('fa-closed-captioning', "Closed captioning"),
    ('fa-cloud', "Cloud"),
    ('fa-cloud-download-alt', "Cloud download alt"),
    ('fa-cloud-upload-alt', "Cloud upload alt"),
    ('fa-cloudscale', "Cloudscale"),
    ('fa-cloudsmith', "Cloudsmith"),
    ('fa-cloudversify', "Cloudversify"),
    ('fa-code', "Code"),
    ('fa-code-branch', "Code branch"),
    ('fa-codepen', "Codepen"),
    ('fa-codiepie', "Codiepie"),
    ('fa-coffee', "Coffee"),
    ('fa-cog', "Cog"),
    ('fa-cogs', "Cogs"),
    ('fa-columns', "Columns"),
    ('fa-comment', "Comment"),
    ('fa-comment-alt', "Comment alt"),
    ('fa-comments', "Comments"),
    ('fa-compass', "Compass"),
    ('fa-compress', "Compress"),
    ('fa-connectdevelop', "Connect Develop"),
    ('fa-contao', "Contao"),
    ('fa-copy', "Copy"),
    ('fa-copyright', "Copyright"),
    ('fa-cpanel', "Cpanel"),
    ('fa-creative-commons', "Creative commons"),
    ('fa-credit-card', "Credit card"),
    ('fa-crop', "Crop"),
    ('fa-crosshairs', "Crosshairs"),
    ('fa-css3', "Css3"),
    ('fa-css3-alt', "Css3 alt"),
    ('fa-cube', "Cube"),
    ('fa-cubes', "Cubes"),
    ('fa-cut', "Cut"),
    ('fa-cuttlefish', "Cuttlefish"),
    ('fa-d-and-d', "D and d"),
    ('fa-dashcube', "Dashcube"),
    ('fa-database', "Database"),
    ('fa-deaf', "Deaf"),
    ('fa-delicious', "Delicious"),
    ('fa-deploydog', "Deploydog"),
    ('fa-deskpro', "Deskpro"),
    ('fa-desktop', "Desktop"),
    ('fa-deviantart', "Deviantart"),
    ('fa-digg', "Digg"),
    ('fa-digital-ocean', "Digital ocean"),
    ('fa-discord', "Discord"),
    ('fa-discourse', "Discourse"),
    ('fa-dochub', "Dochub"),
    ('fa-docker', "Docker"),
    ('fa-dollar-sign', "Dollar sign"),
    ('fa-dot-circle', "Dot circle"),
    ('fa-dot-circle', "Dot circle"),
    ('fa-download', "Download"),
    ('fa-draft2digital', "Draft2digital"),
    ('fa-dribbble', "Dribbble"),
    ('fa-dribbble-square', "Dribbble square"),
    ('fa-dropbox', "Dropbox"),
    ('fa-drupal', "Drupal"),
    ('fa-dyalog', "Dyalog"),
    ('fa-earlybirds', "Earlybirds"),
    ('fa-edge', "Edge"),
    ('fa-edit', "Edit"),
    ('fa-edit', "Edit"),
    ('fa-eject', "Eject"),
    ('fa-elementor', "Elementor"),
    ('fa-ellipsis-h', "Ellipsis h"),
    ('fa-ellipsis-v', "Ellipsis v"),
    ('fa-ember', "Ember"),
    ('fa-empire', "Empire"),
    ('fa-envelope', "Envelope"),
    ('fa-envelope', "Envelope"),
    ('fa-envelope-open', "Envelope open"),
    ('fa-envelope-open', "Envelope open"),
    ('fa-envelope-square', "Envelope square"),
    ('fa-envira', "Envira"),
    ('fa-eraser', "Eraser"),
    ('fa-erlang', "Erlang"),
    ('fa-ethereum', "Ethereum"),
    ('fa-etsy', "Etsy"),
    ('fa-euro-sign', "Euro sign"),
    ('fa-exchange-alt', "Exchange alt"),
    ('fa-exclamation', "Exclamation"),
    ('fa-exclamation-circle', "Exclamation circle"),
    ('fa-exclamation-triangle', "Exclamation triangle"),
    ('fa-expand', "Expand"),
    ('fa-expand-arrows-alt', "Expand arrows alt"),
    ('fa-expeditedssl', "Expeditedssl"),
    ('fa-external-link-alt', "External link alt"),
    ('fa-external-link-square-alt', "External link square alt"),
    ('fa-eye', "Eye"),
    ('fa-eye-dropper', "Eye dropper"),
    ('fa-eye-slash', "Eye slash"),
    ('fa-eye-slash', "Eye slash"),
    ('fa-facebook', "Facebook"),
    ('fa-facebook-f', "Facebook f"),
    ('fa-facebook-messenger', "Facebook messenger"),
    ('fa-facebook-square', "Facebook square"),
    ('fa-fast-backward', "Fast backward"),
    ('fa-fast-forward', "Fast forward"),
    ('fa-fax', "Fax"),
    ('fa-female', "Female"),
    ('fa-fighter-jet', "Fighter jet"),
    ('fa-file', "File"),
    ('fa-file', "File"),
    ('fa-file-alt', "File alt"),
    ('fa-file-alt', "File alt"),
    ('fa-file-archive', "File archive"),
    ('fa-file-archive', "File archive"),
    ('fa-file-audio', "File audio"),
    ('fa-file-audio', "File audio"),
    ('fa-file-code', "File code"),
    ('fa-file-code', "File code"),
    ('fa-file-excel', "File excel"),
    ('fa-file-excel', "File excel"),
    ('fa-file-image', "File image"),
    ('fa-file-image', "File image"),
    ('fa-file-pdf', "File pdf"),
    ('fa-file-pdf', "File pdf"),
    ('fa-file-powerpoint', "File powerpoint"),
    ('fa-file-powerpoint', "File powerpoint"),
    ('fa-file-video', "File video"),
    ('fa-file-video', "File video"),
    ('fa-file-word', "File word"),
    ('fa-file-word', "File word"),
    ('fa-film', "Film"),
    ('fa-filter', "Filter"),
    ('fa-fire', "Fire"),
    ('fa-fire-extinguisher', "Fire extinguisher"),
    ('fa-firefox', "Firefox"),
    ('fa-first-order', "First order"),
    ('fa-firstdraft', "Firstdraft"),
    ('fa-flag', "Flag"),
    ('fa-flag', "Flag"),
    ('fa-flag-checkered', "Flag checkered"),
    ('fa-flask', "Flask"),
    ('fa-flickr', "Flickr"),
    ('fa-flipboard', "Flipboard"),
    ('fa-fly', "Fly"),
    ('fa-folder', "Folder"),
    ('fa-folder', "Folder"),
    ('fa-folder-open', "Folder open"),
    ('fa-folder-open', "Folder open"),
    ('fa-font', "Font"),
    ('fa-font-awesome', "Font awesome"),
    ('fa-font-awesome-alt', "Font awesome alt"),
    ('fa-font-awesome-flag', "Font awesome flag"),
    ('fa-fonticons', "Fonticons"),
    ('fa-fonticons-fi', "Fonticons fi"),
    ('fa-football-ball', "Football ball"),
    ('fa-fort-awesome', "Fort awesome"),
    ('fa-fort-awesome-alt', "Fort awesome alt"),
    ('fa-forumbee', "Forumbee"),
    ('fa-forward', "Forward"),
    ('fa-foursquare', "Foursquare"),
    ('fa-free-code-camp', "Free code camp"),
    ('fa-freebsd', "Freebsd"),
    ('fa-frown', "Frown"),
    ('fa-frown', "Frown"),
    ('fa-futbol', "Futbol"),
    ('fa-futbol', "Futbol"),
    ('fa-gamepad', "Gamepad"),
    ('fa-gavel', "Gavel"),
    ('fa-gem', "Gem"),
    ('fa-gem', "Gem"),
    ('fa-genderless', "Genderless"),
    ('fa-get-pocket', "Get pocket"),
    ('fa-gg', "Gg"),
    ('fa-gg-circle', "Gg circle"),
    ('fa-gift', "Gift"),
    ('fa-git', "Git"),
    ('fa-git-square', "Git square"),
    ('fa-github', "Github"),
    ('fa-github-alt', "Github alt"),
    ('fa-github-square', "Github square"),
    ('fa-gitkraken', "Gitkraken"),
    ('fa-gitlab', "Gitlab"),
    ('fa-gitter', "Gitter"),
    ('fa-glass-martini', "Glass martini"),
    ('fa-glide', "Glide"),
    ('fa-glide-g', "Glide g"),
    ('fa-globe', "Globe"),
    ('fa-gofore', "Gofore"),
    ('fa-golf-ball', "Golf ball"),
    ('fa-goodreads', "Goodreads"),
    ('fa-goodreads-g', "Goodreads g"),
    ('fa-google', "Google"),
    ('fa-google-drive', "Google drive"),
    ('fa-google-play', "Google play"),
    ('fa-google-plus', "Google plus"),
    ('fa-google-plus-g', "Google plus g"),
    ('fa-google-plus-square', "Google plus square"),
    ('fa-google-wallet', "Google wallet"),
    ('fa-graduation-cap', "Graduation cap"),
    ('fa-gratipay', "Gratipay"),
    ('fa-grav', "Grav"),
    ('fa-gripfire', "Gripfire"),
    ('fa-grunt', "Grunt"),
    ('fa-gulp', "Gulp"),
    ('fa-h-square', "H square"),
    ('fa-hacker-news', "Hacker news"),
    ('fa-hacker-news-square', "Hacker news square"),
    ('fa-hand-lizard', "Hand lizard"),
    ('fa-hand-lizard', "Hand lizard"),
    ('fa-hand-paper', "Hand paper"),
    ('fa-hand-paper', "Hand paper"),
    ('fa-hand-peace', "Hand peace"),
    ('fa-hand-peace', "Hand peace"),
    ('fa-hand-point-down', "Hand point down"),
    ('fa-hand-point-down', "Hand point down"),
    ('fa-hand-point-left', "Hand point left"),
    ('fa-hand-point-left', "Hand point left"),
    ('fa-hand-point-right', "Hand point right"),
    ('fa-hand-point-right', "Hand point right"),
    ('fa-hand-point-up', "Hand point up"),
    ('fa-hand-point-up', "Hand point up"),
    ('fa-hand-pointer', "Hand pointer"),
    ('fa-hand-pointer', "Hand pointer"),
    ('fa-hand-rock', "Hand rock"),
    ('fa-hand-rock', "Hand rock"),
    ('fa-hand-scissors', "Hand scissors"),
    ('fa-hand-scissors', "Hand scissors"),
    ('fa-hand-spock', "Hand spock"),
    ('fa-hand-spock', "Hand spock"),
    ('fa-handshake', "Handshake"),
    ('fa-handshake', "Handshake"),
    ('fa-hashtag', "Hashtag"),
    ('fa-hdd', "Hdd"),
    ('fa-hdd', "Hdd"),
    ('fa-heading', "Heading"),
    ('fa-headphones', "Headphones"),
    ('fa-heart', "Heart"),
    ('fa-heart', "Heart"),
    ('fa-heartbeat', "Heartbeat"),
    ('fa-hips', "Hips"),
    ('fa-hire-a-helper', "Hire a helper"),
    ('fa-history', "History"),
    ('fa-hockey-puck', "Hockey puck"),
    ('fa-home', "Home"),
    ('fa-hooli', "Hooli"),
    ('fa-hospital', "Hospital"),
    ('fa-hospital', "Hospital"),
    ('fa-hotjar', "Hotjar"),
    ('fa-hourglass', "Hourglass"),
    ('fa-hourglass', "Hourglass"),
    ('fa-hourglass-end', "Hourglass end"),
    ('fa-hourglass-half', "Hourglass half"),
    ('fa-hourglass-start', "Hourglass start"),
    ('fa-houzz', "Houzz"),
    ('fa-html5', "Html5"),
    ('fa-hubspot', "Hubspot"),
    ('fa-i-cursor', "I cursor"),
    ('fa-id-badge', "Id badge"),
    ('fa-id-badge', "Id badge"),
    ('fa-id-card', "Id card"),
    ('fa-id-card', "Id card"),
    ('fa-image', "Image"),
    ('fa-image', "Image"),
    ('fa-images', "Images"),
    ('fa-images', "Images"),
    ('fa-imdb', "Imdb"),
    ('fa-inbox', "Inbox"),
    ('fa-indent', "Indent"),
    ('fa-industry', "Industry"),
    ('fa-info', "Info"),
    ('fa-info-circle', "Info circle"),
    ('fa-instagram', "Instagram"),
    ('fa-internet-explorer', "Internet explorer"),
    ('fa-ioxhost', "Ioxhost"),
    ('fa-italic', "Italic"),
    ('fa-itunes', "Itunes"),
    ('fa-itunes-note', "Itunes note"),
    ('fa-jenkins', "Jenkins"),
    ('fa-joget', "Joget"),
    ('fa-joomla', "Joomla"),
    ('fa-js', "Js"),
    ('fa-js-square', "Js square"),
    ('fa-jsfiddle', "Jsfiddle"),
    ('fa-key', "Key"),
    ('fa-keyboard', "Keyboard"),
    ('fa-keyboard', "Keyboard"),
    ('fa-keycdn', "Keycdn"),
    ('fa-kickstarter', "Kickstarter"),
    ('fa-kickstarter-k', "Kickstarter k"),
    ('fa-korvue', "Korvue"),
    ('fa-language', "Language"),
    ('fa-laptop', "Laptop"),
    ('fa-laravel', "Laravel"),
    ('fa-lastfm', "Lastfm"),
    ('fa-lastfm-square', "Lastfm square"),
    ('fa-leaf', "Leaf"),
    ('fa-leanpub', "Leanpub"),
    ('fa-lemon', "Lemon"),
    ('fa-lemon', "Lemon"),
    ('fa-less', "Less"),
    ('fa-level-down-alt', "Level down alt"),
    ('fa-level-up-alt', "Level up alt"),
    ('fa-life-ring', "Life ring"),
    ('fa-life-ring', "Life ring"),
    ('fa-lightbulb', "Lightbulb"),
    ('fa-lightbulb', "Lightbulb"),
    ('fa-line', "Line"),
    ('fa-link', "Link"),
    ('fa-linkedin', "Linkedin"),
    ('fa-linkedin-in', "Linkedin in"),
    ('fa-linode', "Linode"),
    ('fa-linux', "Linux"),
    ('fa-lira-sign', "Lira sign"),
    ('fa-list', "List"),
    ('fa-list-alt', "List alt"),
    ('fa-list-alt', "List alt"),
    ('fa-list-ol', "List ol"),
    ('fa-list-ul', "List ul"),
    ('fa-location-arrow', "Location arrow"),
    ('fa-lock', "Lock"),
    ('fa-lock-open', "Lock open"),
    ('fa-long-arrow-alt-down', "Long arrow alt down"),
    ('fa-long-arrow-alt-left', "Long arrow alt left"),
    ('fa-long-arrow-alt-right', "Long arrow alt right"),
    ('fa-long-arrow-alt-up', "Long arrow alt up"),
    ('fa-low-vision', "Low vision"),
    ('fa-lyft', "Lyft"),
    ('fa-magento', "Magento"),
    ('fa-magic', "Magic"),
    ('fa-magnet', "Magnet"),
    ('fa-male', "Male"),
    ('fa-map', "Map"),
    ('fa-map', "Map"),
    ('fa-map-marker', "Map marker"),
    ('fa-map-marker-alt', "Map marker alt"),
    ('fa-map-pin', "Map pin"),
    ('fa-map-signs', "Map signs"),
    ('fa-mars', "Mars"),
    ('fa-mars-double', "Mars double"),
    ('fa-mars-stroke', "Mars stroke"),
    ('fa-mars-stroke-h', "Mars stroke h"),
    ('fa-mars-stroke-v', "Mars stroke v"),
    ('fa-maxcdn', "Maxcdn"),
    ('fa-medapps', "Medapps"),
    ('fa-medium', "Medium"),
    ('fa-medium-m', "Medium m"),
    ('fa-medkit', "Medkit"),
    ('fa-medrt', "Medrt"),
    ('fa-meetup', "Meetup"),
    ('fa-meh', "Meh"),
    ('fa-meh', "Meh"),
    ('fa-mercury', "Mercury"),
    ('fa-microchip', "Microchip"),
    ('fa-microphone', "Microphone"),
    ('fa-microphone-slash', "Microphone slash"),
    ('fa-microsoft', "Microsoft"),
    ('fa-minus', "Minus"),
    ('fa-minus-circle', "Minus circle"),
    ('fa-minus-square', "Minus square"),
    ('fa-minus-square', "Minus square"),
    ('fa-mix', "Mix"),
    ('fa-mixcloud', "Mixcloud"),
    ('fa-mizuni', "Mizuni"),
    ('fa-mobile', "Mobile"),
    ('fa-mobile-alt', "Mobile alt"),
    ('fa-modx', "Modx"),
    ('fa-monero', "Monero"),
    ('fa-money-bill-alt', "Money bill alt"),
    ('fa-money-bill-alt', "Money bill alt"),
    ('fa-moon', "Moon"),
    ('fa-moon', "Moon"),
    ('fa-motorcycle', "Motorcycle"),
    ('fa-mouse-pointer', "Mouse pointer"),
    ('fa-music', "Music"),
    ('fa-napster', "Napster"),
    ('fa-neuter', "Neuter"),
    ('fa-newspaper', "Newspaper"),
    ('fa-newspaper', "Newspaper"),
    ('fa-nintendo-switch', "Nintendo switch"),
    ('fa-node', "Node"),
    ('fa-node-js', "Node js"),
    ('fa-npm', "Npm"),
    ('fa-ns8', "Ns8"),
    ('fa-nutritionix', "Nutritionix"),
    ('fa-object-group', "Object group"),
    ('fa-object-group', "Object group"),
    ('fa-object-ungroup', "Object ungroup"),
    ('fa-object-ungroup', "Object ungroup"),
    ('fa-odnoklassniki', "Odnoklassniki"),
    ('fa-odnoklassniki-square', "Odnoklassniki square"),
    ('fa-opencart', "Opencart"),
    ('fa-openid', "Openid"),
    ('fa-opera', "Opera"),
    ('fa-optin-monster', "Optin monster"),
    ('fa-osi', "Osi"),
    ('fa-outdent', "Outdent"),
    ('fa-page4', "Page4"),
    ('fa-pagelines', "Pagelines"),
    ('fa-paint-brush', "Paint brush"),
    ('fa-palfed', "Palfed"),
    ('fa-paper-plane', "Paper plane"),
    ('fa-paper-plane', "Paper plane"),
    ('fa-paperclip', "Paperclip"),
    ('fa-paragraph', "Paragraph"),
    ('fa-paste', "Paste"),
    ('fa-patreon', "Patreon"),
    ('fa-pause', "Pause"),
    ('fa-pause-circle', "Pause circle"),
    ('fa-pause-circle', "Pause circle"),
    ('fa-paw', "Paw"),
    ('fa-paypal', "Paypal"),
    ('fa-pen-square', "Pen square"),
    ('fa-pencil-alt', "Pencil alt"),
    ('fa-percent', "Percent"),
    ('fa-periscope', "Periscope"),
    ('fa-phabricator', "Phabricator"),
    ('fa-phoenix-framework', "Phoenix framework"),
    ('fa-phone', "Phone"),
    ('fa-phone-square', "Phone square"),
    ('fa-phone-volume', "Phone volume"),
    ('fa-php', "Php"),
    ('fa-pied-piper', "Pied piper"),
    ('fa-pied-piper-alt', "Pied piper alt"),
    ('fa-pied-piper-pp', "Pied piper pp"),
    ('fa-pinterest', "Pinterest"),
    ('fa-pinterest-p', "Pinterest p"),
    ('fa-pinterest-square', "Pinterest square"),
    ('fa-plane', "Plane"),
    ('fa-play', "Play"),
    ('fa-play-circle', "Play circle"),
    ('fa-play-circle', "Play circle"),
    ('fa-playstation', "Playstation"),
    ('fa-plug', "Plug"),
    ('fa-plus', "Plus"),
    ('fa-plus-circle', "Plus circle"),
    ('fa-plus-square', "Plus square"),
    ('fa-plus-square', "Plus square"),
    ('fa-podcast', "Podcast"),
    ('fa-pound-sign', "Pound sign"),
    ('fa-power-off', "Power off"),
    ('fa-print', "Print"),
    ('fa-product-hunt', "Product hunt"),
    ('fa-pushed', "Pushed"),
    ('fa-puzzle-piece', "Puzzle piece"),
    ('fa-python', "Python"),
    ('fa-qq', "Qq"),
    ('fa-qrcode', "Qrcode"),
    ('fa-question', "Question"),
    ('fa-question-circle', "Question circle"),
    ('fa-question-circle', "Question circle"),
    ('fa-quidditch', "Quidditch"),
    ('fa-quinscape', "Quinscape"),
    ('fa-quora', "Quora"),
    ('fa-quote-left', "Quote left"),
    ('fa-quote-right', "Quote right"),
    ('fa-random', "Random"),
    ('fa-ravelry', "Ravelry"),
    ('fa-react', "React"),
    ('fa-rebel', "Rebel"),
    ('fa-recycle', "Recycle"),
    ('fa-red-river', "Red river"),
    ('fa-reddit', "Reddit"),
    ('fa-reddit-alien', "Reddit alien"),
    ('fa-reddit-square', "Reddit square"),
    ('fa-redo', "Redo"),
    ('fa-redo-alt', "Redo alt"),
    ('fa-registered', "Registered"),
    ('fa-registered', "Registered"),
    ('fa-rendact', "Rendact"),
    ('fa-renren', "Renren"),
    ('fa-reply', "Reply"),
    ('fa-reply-all', "Reply all"),
    ('fa-replyd', "Replyd"),
    ('fa-resolving', "Resolving"),
    ('fa-retweet', "Retweet"),
    ('fa-road', "Road"),
    ('fa-rocket', "Rocket"),
    ('fa-rocketchat', "Rocketchat"),
    ('fa-rockrms', "Rockrms"),
    ('fa-rss', "Rss"),
    ('fa-rss-square', "Rss square"),
    ('fa-ruble-sign', "Ruble sign"),
    ('fa-rupee-sign', "Rupee sign"),
    ('fa-safari', "Safari"),
    ('fa-sass', "Sass"),
    ('fa-save', "Save"),
    ('fa-save', "Save"),
    ('fa-schlix', "Schlix"),
    ('fa-scribd', "Scribd"),
    ('fa-search', "Search"),
    ('fa-search-minus', "Search minus"),
    ('fa-search-plus', "Search plus"),
    ('fa-searchengin', "Searchengin"),
    ('fa-sellcast', "Sellcast"),
    ('fa-sellsy', "Sellsy"),
    ('fa-server', "Server"),
    ('fa-servicestack', "Servicestack"),
    ('fa-share', "Share"),
    ('fa-share-alt', "Share alt"),
    ('fa-share-alt-square', "Share alt square"),
    ('fa-share-square', "Share square"),
    ('fa-share-square', "Share square"),
    ('fa-shekel-sign', "Shekel sign"),
    ('fa-shield-alt', "Shield alt"),
    ('fa-ship', "Ship"),
    ('fa-shirtsinbulk', "Shirtsinbulk"),
    ('fa-shopping-bag', "Shopping bag"),
    ('fa-shopping-basket', "Shopping basket"),
    ('fa-shopping-cart', "Shopping cart"),
    ('fa-shower', "Shower"),
    ('fa-sign-in-alt', "Sign in alt"),
    ('fa-sign-language', "Sign language"),
    ('fa-sign-out-alt', "Sign out alt"),
    ('fa-signal', "Signal"),
    ('fa-simplybuilt', "Simplybuilt"),
    ('fa-sistrix', "Sistrix"),
    ('fa-sitemap', "Sitemap"),
    ('fa-skyatlas', "Skyatlas"),
    ('fa-skype', "Skype"),
    ('fa-slack', "Slack"),
    ('fa-slack-hash', "Slack hash"),
    ('fa-sliders-h', "Sliders h"),
    ('fa-slideshare', "Slideshare"),
    ('fa-smile', "Smile"),
    ('fa-smile', "Smile"),
    ('fa-snapchat', "Snapchat"),
    ('fa-snapchat-ghost', "Snapchat ghost"),
    ('fa-snapchat-square', "Snapchat square"),
    ('fa-snowflake', "Snowflake"),
    ('fa-snowflake', "Snowflake"),
    ('fa-sort', "Sort"),
    ('fa-sort-alpha-down', "Sort alpha down"),
    ('fa-sort-alpha-up', "Sort alpha up"),
    ('fa-sort-amount-down', "Sort amount down"),
    ('fa-sort-amount-up', "Sort amount up"),
    ('fa-sort-down', "Sort down"),
    ('fa-sort-numeric-down', "Sort numeric down"),
    ('fa-sort-numeric-up', "Sort numeric up"),
    ('fa-sort-up', "Sort up"),
    ('fa-soundcloud', "Soundcloud"),
    ('fa-space-shuttle', "Space shuttle"),
    ('fa-speakap', "Speakap"),
    ('fa-spinner', "Spinner"),
    ('fa-spotify', "Spotify"),
    ('fa-square', "Square"),
    ('fa-square', "Square"),
    ('fa-square-full', "Square full"),
    ('fa-stack-exchange', "Stack exchange"),
    ('fa-stack-overflow', "Stack overflow"),
    ('fa-star', "Star"),
    ('fa-star', "Star"),
    ('fa-star-half', "Star half"),
    ('fa-star-half', "Star half"),
    ('fa-staylinked', "Staylinked"),
    ('fa-steam', "Steam"),
    ('fa-steam-square', "Steam square"),
    ('fa-steam-symbol', "Steam symbol"),
    ('fa-step-backward', "Step backward"),
    ('fa-step-forward', "Step forward"),
    ('fa-stethoscope', "Stethoscope"),
    ('fa-sticker-mule', "Sticker mule"),
    ('fa-sticky-note', "Sticky note"),
    ('fa-sticky-note', "Sticky note"),
    ('fa-stop', "Stop"),
    ('fa-stop-circle', "Stop circle"),
    ('fa-stop-circle', "Stop circle"),
    ('fa-stopwatch', "Stopwatch"),
    ('fa-strava', "Strava"),
    ('fa-street-view', "Street view"),
    ('fa-strikethrough', "Strikethrough"),
    ('fa-stripe', "Stripe"),
    ('fa-stripe-s', "Stripe s"),
    ('fa-studiovinari', "Studiovinari"),
    ('fa-stumbleupon', "Stumbleupon"),
    ('fa-stumbleupon-circle', "Stumbleupon circle"),
    ('fa-subscript', "Subscript"),
    ('fa-subway', "Subway"),
    ('fa-suitcase', "Suitcase"),
    ('fa-sun', "Sun"),
    ('fa-sun', "Sun"),
    ('fa-superpowers', "Superpowers"),
    ('fa-superscript', "Superscript"),
    ('fa-supple', "Supple"),
    ('fa-sync', "Sync"),
    ('fa-sync-alt', "Sync alt"),
    ('fa-table', "Table"),
    ('fa-table-tennis', "Table tennis"),
    ('fa-tablet', "Tablet"),
    ('fa-tablet-alt', "Tablet alt"),
    ('fa-tachometer-alt', "Tachometer alt"),
    ('fa-tag', "Tag"),
    ('fa-tags', "Tags"),
    ('fa-tasks', "Tasks"),
    ('fa-taxi', "Taxi"),
    ('fa-telegram', "Telegram"),
    ('fa-telegram-plane', "Telegram plane"),
    ('fa-tencent-weibo', "Tencent weibo"),
    ('fa-terminal', "Terminal"),
    ('fa-text-height', "Text height"),
    ('fa-text-width', "Text width"),
    ('fa-th', "Th"),
    ('fa-th-large', "Th large"),
    ('fa-th-list', "Th list"),
    ('fa-themeisle', "Themeisle"),
    ('fa-thermometer-empty', "Thermometer empty"),
    ('fa-thermometer-full', "Thermometer full"),
    ('fa-thermometer-half', "Thermometer half"),
    ('fa-thermometer-quarter', "Thermometer quarter"),
    ('fa-thermometer-three-quarters', "Thermometer three quarters"),
    ('fa-thumbs-down', "Thumbs down"),
    ('fa-thumbs-down', "Thumbs down"),
    ('fa-thumbs-up', "Thumbs up"),
    ('fa-thumbs-up', "Thumbs up"),
    ('fa-thumbtack', "Thumbtack"),
    ('fa-ticket-alt', "Ticket alt"),
    ('fa-times', "Times"),
    ('fa-times-circle', "Times circle"),
    ('fa-times-circle', "Times circle"),
    ('fa-tint', "Tint"),
    ('fa-toggle-off', "Toggle off"),
    ('fa-toggle-on', "Toggle on"),
    ('fa-trademark', "Trademark"),
    ('fa-train', "Train"),
    ('fa-transgender', "Transgender"),
    ('fa-transgender-alt', "Transgender alt"),
    ('fa-trash', "Trash"),
    ('fa-trash-alt', "Trash alt"),
    ('fa-trash-alt', "Trash alt"),
    ('fa-tree', "Tree"),
    ('fa-trello', "Trello"),
    ('fa-tripadvisor', "Tripadvisor"),
    ('fa-trophy', "Trophy"),
    ('fa-truck', "Truck"),
    ('fa-tty', "Tty"),
    ('fa-tumblr', "Tumblr"),
    ('fa-tumblr-square', "Tumblr square"),
    ('fa-tv', "Tv"),
    ('fa-twitch', "Twitch"),
    ('fa-twitter', "Twitter"),
    ('fa-twitter-square', "Twitter square"),
    ('fa-typo3', "Typo3"),
    ('fa-uber', "Uber"),
    ('fa-uikit', "Uikit"),
    ('fa-umbrella', "Umbrella"),
    ('fa-underline', "Underline"),
    ('fa-undo', "Undo"),
    ('fa-undo-alt', "Undo alt"),
    ('fa-uniregistry', "Uniregistry"),
    ('fa-universal-access', "Universal access"),
    ('fa-university', "University"),
    ('fa-unlink', "Unlink"),
    ('fa-unlock', "Unlock"),
    ('fa-unlock-alt', "Unlock alt"),
    ('fa-untappd', "Untappd"),
    ('fa-upload', "Upload"),
    ('fa-usb', "Usb"),
    ('fa-user', "User"),
    ('fa-user', "User"),
    ('fa-user-circle', "User circle"),
    ('fa-user-circle', "User circle"),
    ('fa-user-md', "User md"),
    ('fa-user-plus', "User plus"),
    ('fa-user-secret', "User secret"),
    ('fa-user-times', "User times"),
    ('fa-users', "Users"),
    ('fa-ussunnah', "Ussunnah"),
    ('fa-utensil-spoon', "Utensil spoon"),
    ('fa-utensils', "Utensils"),
    ('fa-vaadin', "Vaadin"),
    ('fa-venus', "Venus"),
    ('fa-venus-double', "Venus double"),
    ('fa-venus-mars', "Venus mars"),
    ('fa-viacoin', "Viacoin"),
    ('fa-viadeo', "Viadeo"),
    ('fa-viadeo-square', "Viadeo square"),
    ('fa-viber', "Viber"),
    ('fa-video', "Video"),
    ('fa-vimeo', "Vimeo"),
    ('fa-vimeo-square', "Vimeo square"),
    ('fa-vimeo-v', "Vimeo v"),
    ('fa-vine', "Vine"),
    ('fa-vk', "Vk"),
    ('fa-vnv', "Vnv"),
    ('fa-volleyball-ball', "Volleyball ball"),
    ('fa-volume-down', "Volume down"),
    ('fa-volume-off', "Volume off"),
    ('fa-volume-up', "Volume up"),
    ('fa-vuejs', "Vuejs"),
    ('fa-weibo', "Weibo"),
    ('fa-weixin', "Weixin"),
    ('fa-whatsapp', "Whatsapp"),
    ('fa-whatsapp-square', "Whatsapp square"),
    ('fa-wheelchair', "Wheelchair"),
    ('fa-whmcs', "Whmcs"),
    ('fa-wifi', "Wifi"),
    ('fa-wikipedia-w', "Wikipedia w"),
    ('fa-window-close', "Window close"),
    ('fa-window-close', "Window close"),
    ('fa-window-maximize', "Window maximize"),
    ('fa-window-maximize', "Window maximize"),
    ('fa-window-minimize', "Window minimize"),
    ('fa-window-minimize', "Window minimize"),
    ('fa-window-restore', "Window restore"),
    ('fa-window-restore', "Window restore"),
    ('fa-windows', "Windows"),
    ('fa-won-sign', "Won sign"),
    ('fa-wordpress', "Wordpress"),
    ('fa-wordpress-simple', "Wordpress simple"),
    ('fa-wpbeginner', "Wpbeginner"),
    ('fa-wpexplorer', "Wpexplorer"),
    ('fa-wpforms', "Wpforms"),
    ('fa-wrench', "Wrench"),
    ('fa-xbox', "Xbox"),
    ('fa-xing', "Xing"),
    ('fa-xing-square', "Xing square"),
    ('fa-y-combinator', "Y combinator"),
    ('fa-yahoo', "Yahoo"),
    ('fa-yandex', "Yandex"),
    ('fa-yandex-international', "Yandex international"),
    ('fa-yelp', "Yelp"),
    ('fa-yen-sign', "Yen sign"),
    ('fa-yoast', "Yoast"),
    ('fa-youtube', "Youtube"),
    ('fa-youtube-square', "Youtube square"),
]
